/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Access-Platforms-Even-Sectors-cut1.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Floor003: THREE.Mesh;
    Handrail003: THREE.Mesh;
    construct003: THREE.Mesh;
  };
  materials: {
    _00000246D20E9CE0: THREE.MeshStandardMaterial;
    _00000246D20EA8B0: THREE.MeshStandardMaterial;
    _00000246D20EAA00: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Access-Platforms-Even-Sectors-cut1-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Floor003.geometry} material={materials._00000246D20E9CE0} />
      <mesh geometry={nodes.Handrail003.geometry} material={materials._00000246D20EA8B0} />
      <mesh geometry={nodes.construct003.geometry} material={materials._00000246D20EAA00} />
    </group>
  );
}

useGLTF.preload("/Access-Platforms-Even-Sectors-cut1-transformed.glb");
