/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Access-Platforms-Even-Sectors-cut4.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Floor005: THREE.Mesh;
    construct005: THREE.Mesh;
    Handrail004: THREE.Mesh;
  };
  materials: {
    _00000214FE88A840: THREE.MeshStandardMaterial;
    _00000214FE88AC30: THREE.MeshStandardMaterial;
    _00000214FE88AED0: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Access-Platforms-Even-Sectors-cut4-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Floor005.geometry} material={materials._00000214FE88A840} />
      <mesh geometry={nodes.construct005.geometry} material={materials._00000214FE88AC30} />
      <mesh geometry={nodes.Handrail004.geometry} material={materials._00000214FE88AED0} />
    </group>
  );
}

useGLTF.preload("/Access-Platforms-Even-Sectors-cut4-transformed.glb");
