/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Access-Platforms-Odd-Sectors-cut3.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Floor003: THREE.Mesh;
    Handrail003: THREE.Mesh;
    construct003: THREE.Mesh;
  };
  materials: {
    _000001CC495569E0: THREE.MeshStandardMaterial;
    _000001CC49558570: THREE.MeshStandardMaterial;
    _000001CC49558FF0: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Access-Platforms-Odd-Sectors-cut3-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Floor003.geometry} material={materials._000001CC495569E0} />
      <mesh geometry={nodes.Handrail003.geometry} material={materials._000001CC49558570} />
      <mesh geometry={nodes.construct003.geometry} material={materials._000001CC49558FF0} />
    </group>
  );
}

useGLTF.preload("/Access-Platforms-Odd-Sectors-cut3-transformed.glb");
