/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Access-Platforms-Even-Sectors-cut3.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    construct001: THREE.Mesh;
    Handrail001: THREE.Mesh;
    Floor001: THREE.Mesh;
  };
  materials: {
    ["_00000264581E3560.001"]: THREE.MeshStandardMaterial;
    ["_00000264581E3950.001"]: THREE.MeshStandardMaterial;
    ["_00000264581E3BF0.001"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Access-Platforms-Even-Sectors-cut3-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.construct001.geometry} material={materials["_00000264581E3560.001"]} />
      <mesh geometry={nodes.Handrail001.geometry} material={materials["_00000264581E3950.001"]} />
      <mesh geometry={nodes.Floor001.geometry} material={materials["_00000264581E3BF0.001"]} />
    </group>
  );
}

useGLTF.preload("/Access-Platforms-Even-Sectors-cut3-transformed.glb");
