/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Access-Platforms-Odd-Sectors.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Handrail: THREE.Mesh;
    Floor004: THREE.Mesh;
    construct004: THREE.Mesh;
  };
  materials: {
    _000001CC49560B50: THREE.MeshStandardMaterial;
    _000001CC49562EC0: THREE.MeshStandardMaterial;
    _000001CC495632B0: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Access-Platforms-Odd-Sectors-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Handrail.geometry} material={materials._000001CC49560B50} />
      <mesh geometry={nodes.Floor004.geometry} material={materials._000001CC49562EC0} />
      <mesh geometry={nodes.construct004.geometry} material={materials._000001CC495632B0} />
    </group>
  );
}

useGLTF.preload("/Access-Platforms-Odd-Sectors-transformed.glb");
