/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Access-Platforms-Odd-Sectors-cut2.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Floor002: THREE.Mesh;
    construct002: THREE.Mesh;
    Handrail002: THREE.Mesh;
  };
  materials: {
    _000001CC2FD7B460: THREE.MeshStandardMaterial;
    _000001CC2FD7B700: THREE.MeshStandardMaterial;
    _000001CC2FD7B9A0: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Access-Platforms-Odd-Sectors-cut2-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Floor002.geometry} material={materials._000001CC2FD7B460} />
      <mesh geometry={nodes.construct002.geometry} material={materials._000001CC2FD7B700} />
      <mesh geometry={nodes.Handrail002.geometry} material={materials._000001CC2FD7B9A0} />
    </group>
  );
}

useGLTF.preload("/Access-Platforms-Odd-Sectors-cut2-transformed.glb");
