/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Access-Platforms-Odd-Sectors-cut4.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Floor: THREE.Mesh;
    construct: THREE.Mesh;
    Handrail004: THREE.Mesh;
  };
  materials: {
    _000001CC46FA9EE0: THREE.MeshStandardMaterial;
    _000001CC46FAA030: THREE.MeshStandardMaterial;
    _000001CC46FABE60: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Access-Platforms-Odd-Sectors-cut4-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Floor.geometry} material={materials._000001CC46FA9EE0} />
      <mesh geometry={nodes.construct.geometry} material={materials._000001CC46FAA030} />
      <mesh geometry={nodes.Handrail004.geometry} material={materials._000001CC46FABE60} />
    </group>
  );
}

useGLTF.preload("/Access-Platforms-Odd-Sectors-cut4-transformed.glb");
