/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Barrel-Toroid.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_1011: THREE.Mesh;
    Mesh_2009: THREE.Mesh;
    Mesh_3003: THREE.Mesh;
    Mesh_4: THREE.Mesh;
    Mesh_5: THREE.Mesh;
  };
  materials: {
    ["Material_1.011"]: THREE.MeshStandardMaterial;
    ["Material_2.009"]: THREE.MeshStandardMaterial;
    ["Material_3.003"]: THREE.MeshStandardMaterial;
    Material_4: THREE.MeshStandardMaterial;
    Material_5: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Barrel-Toroid-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_1011.geometry} material={materials["Material_1.011"]} />
      <mesh geometry={nodes.Mesh_2009.geometry} material={materials["Material_2.009"]} />
      <mesh geometry={nodes.Mesh_3003.geometry} material={materials["Material_3.003"]} />
      <mesh geometry={nodes.Mesh_4.geometry} material={materials.Material_4} />
      <mesh geometry={nodes.Mesh_5.geometry} material={materials.Material_5} />
    </group>
  );
}

useGLTF.preload("/Barrel-Toroid-transformed.glb");
