/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Barrel-Toroid-cut4.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["S_Mesh_0-011"]: THREE.Mesh;
    ["S_Mesh_1-001"]: THREE.Mesh;
    ["S_Mesh_2-001"]: THREE.Mesh;
    ["S_Mesh_3-001"]: THREE.Mesh;
    ["S_Mesh_5-001"]: THREE.Mesh;
  };
  materials: {
    ["Material_Mesh_0-011.019"]: THREE.MeshStandardMaterial;
    ["Material_Mesh_1-001.018"]: THREE.MeshStandardMaterial;
    ["Material_Mesh_2-001.018"]: THREE.MeshStandardMaterial;
    ["Material_Mesh_3-001.018"]: THREE.MeshStandardMaterial;
    ["Material_Mesh_5-001.019"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Barrel-Toroid-cut4-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["S_Mesh_0-011"].geometry}
        material={materials["Material_Mesh_0-011.019"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S_Mesh_1-001"].geometry}
        material={materials["Material_Mesh_1-001.018"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S_Mesh_2-001"].geometry}
        material={materials["Material_Mesh_2-001.018"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S_Mesh_3-001"].geometry}
        material={materials["Material_Mesh_3-001.018"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S_Mesh_5-001"].geometry}
        material={materials["Material_Mesh_5-001.019"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/Barrel-Toroid-cut4-transformed.glb");
