/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Barrel-Toroid-cut2.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0013: THREE.Mesh;
    Mesh_2011: THREE.Mesh;
    Mesh_3005: THREE.Mesh;
    Mesh_4002: THREE.Mesh;
    Mesh_5002: THREE.Mesh;
  };
  materials: {
    ["Material_0.013"]: THREE.MeshStandardMaterial;
    ["Material_2.011"]: THREE.MeshStandardMaterial;
    ["Material_3.005"]: THREE.MeshStandardMaterial;
    ["Material_4.002"]: THREE.MeshStandardMaterial;
    ["Material_5.002"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Barrel-Toroid-cut2-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0013.geometry} material={materials["Material_0.013"]} />
      <mesh geometry={nodes.Mesh_2011.geometry} material={materials["Material_2.011"]} />
      <mesh geometry={nodes.Mesh_3005.geometry} material={materials["Material_3.005"]} />
      <mesh geometry={nodes.Mesh_4002.geometry} material={materials["Material_4.002"]} />
      <mesh geometry={nodes.Mesh_5002.geometry} material={materials["Material_5.002"]} />
    </group>
  );
}

useGLTF.preload("/Barrel-Toroid-cut2-transformed.glb");
