/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Flex-Chain-Sec15-cut1.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _00000197A5EA1A60i_IndexedFaceSet: THREE.Mesh;
    _00000197A5EA1BB0i_IndexedFaceSet: THREE.Mesh;
    _00000197A5EA1E50i_IndexedFaceSet: THREE.Mesh;
    _00000197A5EA2240i_IndexedFaceSet: THREE.Mesh;
    _00000197A5EA2390i_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    _00000197A5EA1A60i: THREE.MeshStandardMaterial;
    _00000197A5EA1BB0i: THREE.MeshStandardMaterial;
    _00000197A5EA1E50i: THREE.MeshStandardMaterial;
    _00000197A5EA2240i: THREE.MeshStandardMaterial;
    _00000197A5EA2390i: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Flex-Chain-Sec15-cut1-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._00000197A5EA1A60i_IndexedFaceSet.geometry} material={materials._00000197A5EA1A60i} />
      <mesh geometry={nodes._00000197A5EA1BB0i_IndexedFaceSet.geometry} material={materials._00000197A5EA1BB0i} />
      <mesh geometry={nodes._00000197A5EA1E50i_IndexedFaceSet.geometry} material={materials._00000197A5EA1E50i} />
      <mesh geometry={nodes._00000197A5EA2240i_IndexedFaceSet.geometry} material={materials._00000197A5EA2240i} />
      <mesh geometry={nodes._00000197A5EA2390i_IndexedFaceSet.geometry} material={materials._00000197A5EA2390i} />
    </group>
  );
}

useGLTF.preload("/Flex-Chain-Sec15-cut1-transformed.glb");
