/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/HF-Truck-SideA-cut2.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _000001571D1F8070_IndexedFaceSet: THREE.Mesh;
    _000001571D1F8460_IndexedFaceSet: THREE.Mesh;
    _000001571D1F8D90_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    _000001571D1F8070: THREE.MeshStandardMaterial;
    _000001571D1F8460: THREE.MeshStandardMaterial;
    _000001571D1F8D90: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/HF-Truck-SideA-cut2-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._000001571D1F8070_IndexedFaceSet.geometry} material={materials._000001571D1F8070} />
      <mesh geometry={nodes._000001571D1F8460_IndexedFaceSet.geometry} material={materials._000001571D1F8460} />
      <mesh geometry={nodes._000001571D1F8D90_IndexedFaceSet.geometry} material={materials._000001571D1F8D90} />
    </group>
  );
}

useGLTF.preload("/HF-Truck-SideA-cut2-transformed.glb");
