/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/HO-side-C-Services-cut3.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _000001D304196090_IndexedFaceSet: THREE.Mesh;
    _000001D30419B730_IndexedFaceSet: THREE.Mesh;
    _000001D30E80B760_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    _000001D304196090: THREE.MeshStandardMaterial;
    _000001D30419B730: THREE.MeshStandardMaterial;
    _000001D30E80B760: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/HO-side-C-Services-cut3-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._000001D304196090_IndexedFaceSet.geometry} material={materials._000001D304196090} />
      <mesh geometry={nodes._000001D30419B730_IndexedFaceSet.geometry} material={materials._000001D30419B730} />
      <mesh geometry={nodes._000001D30E80B760_IndexedFaceSet.geometry} material={materials._000001D30E80B760} />
    </group>
  );
}

useGLTF.preload("/HO-side-C-Services-cut3-transformed.glb");
