/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/HO-side-A-Services-cut2.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _000001BD80990AC0_IndexedFaceSet: THREE.Mesh;
    _000001BD85268BC0_IndexedFaceSet: THREE.Mesh;
    _000001BD86AF9340_IndexedFaceSet: THREE.Mesh;
    _000001BD86F550C0_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    ["_000001BD80990AC0.001"]: THREE.MeshStandardMaterial;
    ["_000001BD85268BC0.001"]: THREE.MeshStandardMaterial;
    ["_000001BD86AF9340.001"]: THREE.MeshStandardMaterial;
    ["_000001BD86F550C0.001"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/HO-side-A-Services-cut2-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._000001BD80990AC0_IndexedFaceSet.geometry} material={materials["_000001BD80990AC0.001"]} />
      <mesh geometry={nodes._000001BD85268BC0_IndexedFaceSet.geometry} material={materials["_000001BD85268BC0.001"]} />
      <mesh geometry={nodes._000001BD86AF9340_IndexedFaceSet.geometry} material={materials["_000001BD86AF9340.001"]} />
      <mesh geometry={nodes._000001BD86F550C0_IndexedFaceSet.geometry} material={materials["_000001BD86F550C0.001"]} />
    </group>
  );
}

useGLTF.preload("/HO-side-A-Services-cut2-transformed.glb");
