/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/HO-Side-C-Platforms-cut3.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _0000014394D4C220_IndexedFaceSet: THREE.Mesh;
    _0000014394D4C370_IndexedFaceSet: THREE.Mesh;
    _0000014394D4C610_IndexedFaceSet: THREE.Mesh;
    _0000014394D4CB50_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    _0000014394D4C220: THREE.MeshStandardMaterial;
    _0000014394D4C370: THREE.MeshStandardMaterial;
    _0000014394D4C610: THREE.MeshStandardMaterial;
    _0000014394D4CB50: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/HO-Side-C-Platforms-cut3-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._0000014394D4C220_IndexedFaceSet.geometry} material={materials._0000014394D4C220} />
      <mesh geometry={nodes._0000014394D4C370_IndexedFaceSet.geometry} material={materials._0000014394D4C370} />
      <mesh geometry={nodes._0000014394D4C610_IndexedFaceSet.geometry} material={materials._0000014394D4C610} />
      <mesh geometry={nodes._0000014394D4CB50_IndexedFaceSet.geometry} material={materials._0000014394D4CB50} />
    </group>
  );
}

useGLTF.preload("/HO-Side-C-Platforms-cut3-transformed.glb");
