/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/HO-Side-C-Platforms-cut4.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _00000241A93F9C90_IndexedFaceSet: THREE.Mesh;
    _00000241E9D19220_IndexedFaceSet: THREE.Mesh;
    _00000241E9D19A00_IndexedFaceSet: THREE.Mesh;
    _00000241E9D1E770_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    L_L_L__00000241A93F9C90: THREE.MeshStandardMaterial;
    _00000241E9D19220: THREE.MeshStandardMaterial;
    _00000241E9D19A00: THREE.MeshStandardMaterial;
    _00000241E9D1E770: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/HO-Side-C-Platforms-cut4-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._00000241A93F9C90_IndexedFaceSet.geometry} material={materials.L_L_L__00000241A93F9C90} />
      <mesh geometry={nodes._00000241E9D19220_IndexedFaceSet.geometry} material={materials._00000241E9D19220} />
      <mesh geometry={nodes._00000241E9D19A00_IndexedFaceSet.geometry} material={materials._00000241E9D19A00} />
      <mesh geometry={nodes._00000241E9D1E770_IndexedFaceSet.geometry} material={materials._00000241E9D1E770} />
    </group>
  );
}

useGLTF.preload("/HO-Side-C-Platforms-cut4-transformed.glb");
