/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/HO-Side-A-Platforms-cut2.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _000002A20C9D44D0_IndexedFaceSet: THREE.Mesh;
    _000002A20C9D5730_IndexedFaceSet: THREE.Mesh;
    _000002A20C9D5880_IndexedFaceSet: THREE.Mesh;
    _000002A20CA10830_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    _000002A20C9D44D0: THREE.MeshStandardMaterial;
    _000002A20C9D5730: THREE.MeshStandardMaterial;
    _000002A20C9D5880: THREE.MeshStandardMaterial;
    _000002A20CA10830: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/HO-Side-A-Platforms-cut2-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._000002A20C9D44D0_IndexedFaceSet.geometry} material={materials._000002A20C9D44D0} />
      <mesh geometry={nodes._000002A20C9D5730_IndexedFaceSet.geometry} material={materials._000002A20C9D5730} />
      <mesh geometry={nodes._000002A20C9D5880_IndexedFaceSet.geometry} material={materials._000002A20C9D5880} />
      <mesh geometry={nodes._000002A20CA10830_IndexedFaceSet.geometry} material={materials._000002A20CA10830} />
    </group>
  );
}

useGLTF.preload("/HO-Side-A-Platforms-cut2-transformed.glb");
