/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/HO-side-C-Services-cut2.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _000001D304198550_IndexedFaceSet: THREE.Mesh;
    _000001D30E800A20_IndexedFaceSet: THREE.Mesh;
    _000001D30E805E20_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    ["_000001D304198550.001"]: THREE.MeshStandardMaterial;
    ["_000001D30E800A20.001"]: THREE.MeshStandardMaterial;
    ["_000001D30E805E20.001"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/HO-side-C-Services-cut2-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._000001D304198550_IndexedFaceSet.geometry} material={materials["_000001D304198550.001"]} />
      <mesh geometry={nodes._000001D30E800A20_IndexedFaceSet.geometry} material={materials["_000001D30E800A20.001"]} />
      <mesh geometry={nodes._000001D30E805E20_IndexedFaceSet.geometry} material={materials["_000001D30E805E20.001"]} />
    </group>
  );
}

useGLTF.preload("/HO-side-C-Services-cut2-transformed.glb");
