/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/HO-side-A-Services-cut3.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _000001D30260A5D0_IndexedFaceSet: THREE.Mesh;
    _000001D302610300_IndexedFaceSet: THREE.Mesh;
    _000001D302716090_IndexedFaceSet: THREE.Mesh;
    _000001D303CBB080_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    ["_000001D30260A5D0.001"]: THREE.MeshStandardMaterial;
    ["_000001D302610300.001"]: THREE.MeshStandardMaterial;
    ["_000001D302716090.001"]: THREE.MeshStandardMaterial;
    ["_000001D303CBB080.001"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/HO-side-A-Services-cut3-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._000001D30260A5D0_IndexedFaceSet.geometry} material={materials["_000001D30260A5D0.001"]} />
      <mesh geometry={nodes._000001D302610300_IndexedFaceSet.geometry} material={materials["_000001D302610300.001"]} />
      <mesh geometry={nodes._000001D302716090_IndexedFaceSet.geometry} material={materials["_000001D302716090.001"]} />
      <mesh geometry={nodes._000001D303CBB080_IndexedFaceSet.geometry} material={materials["_000001D303CBB080.001"]} />
    </group>
  );
}

useGLTF.preload("/HO-side-A-Services-cut3-transformed.glb");
