/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/HS-ARCHE-cut1.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _0000026192FB1880_004_IndexedFaceSet002: THREE.Mesh;
    _0000026192FB1880_004_IndexedFaceSet002_1: THREE.Mesh;
    _00000261AB2A4090_IndexedFaceSet002: THREE.Mesh;
    _00000261AB2A4090_IndexedFaceSet002_1: THREE.Mesh;
    _00000261AB2A67F0_IndexedFaceSet: THREE.Mesh;
    _00000261AB2AD390_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    ["_0000026192FB1880_004.002"]: THREE.MeshStandardMaterial;
    ["_00000261AB2A4090.002"]: THREE.MeshStandardMaterial;
    ["_00000261AB2A67F0.002"]: THREE.MeshStandardMaterial;
    ["_00000261AB2AD390.002"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/HS-ARCHE-cut1-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._00000261AB2A67F0_IndexedFaceSet.geometry} material={materials["_00000261AB2A67F0.002"]} />
      <mesh geometry={nodes._00000261AB2AD390_IndexedFaceSet.geometry} material={materials["_00000261AB2AD390.002"]} />
      <mesh
        geometry={nodes._0000026192FB1880_004_IndexedFaceSet002.geometry}
        material={materials["_0000026192FB1880_004.002"]}
      />
      <mesh
        geometry={nodes._0000026192FB1880_004_IndexedFaceSet002_1.geometry}
        material={nodes._0000026192FB1880_004_IndexedFaceSet002_1.material}
      />
      <mesh
        geometry={nodes._00000261AB2A4090_IndexedFaceSet002.geometry}
        material={materials["_00000261AB2A4090.002"]}
      />
      <mesh
        geometry={nodes._00000261AB2A4090_IndexedFaceSet002_1.geometry}
        material={nodes._00000261AB2A4090_IndexedFaceSet002_1.material}
      />
    </group>
  );
}

useGLTF.preload("/HS-ARCHE-cut1-transformed.glb");
