/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/HS-ARCHE-cut2.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _00000207895ABB30_23_IndexedFaceSet: THREE.Mesh;
    _00000207B58B88B0_041_IndexedFaceSet001: THREE.Mesh;
    _00000207B58B88B0_041_IndexedFaceSet001_1: THREE.Mesh;
    _00000207B58BB400_IndexedFaceSet001: THREE.Mesh;
    _00000207B58BB400_IndexedFaceSet001_1: THREE.Mesh;
    _00000207BBA2FDA0_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    ["_00000207895ABB30_23.001"]: THREE.MeshStandardMaterial;
    ["_00000207B58B88B0_041.001"]: THREE.MeshStandardMaterial;
    ["_00000207B58BB400.001"]: THREE.MeshStandardMaterial;
    ["_00000207BBA2FDA0.001"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/HS-ARCHE-cut2-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes._00000207895ABB30_23_IndexedFaceSet.geometry}
        material={materials["_00000207895ABB30_23.001"]}
      />
      <mesh geometry={nodes._00000207BBA2FDA0_IndexedFaceSet.geometry} material={materials["_00000207BBA2FDA0.001"]} />
      <mesh
        geometry={nodes._00000207B58B88B0_041_IndexedFaceSet001.geometry}
        material={materials["_00000207B58B88B0_041.001"]}
      />
      <mesh
        geometry={nodes._00000207B58B88B0_041_IndexedFaceSet001_1.geometry}
        material={nodes._00000207B58B88B0_041_IndexedFaceSet001_1.material}
      />
      <mesh
        geometry={nodes._00000207B58BB400_IndexedFaceSet001.geometry}
        material={materials["_00000207B58BB400.001"]}
      />
      <mesh
        geometry={nodes._00000207B58BB400_IndexedFaceSet001_1.geometry}
        material={nodes._00000207B58BB400_IndexedFaceSet001_1.material}
      />
    </group>
  );
}

useGLTF.preload("/HS-ARCHE-cut2-transformed.glb");
