/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/HS-CENTRAL-PIT-STRUCTURE.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _000001E91E42F1E0_IndexedFaceSet: THREE.Mesh;
    _000001E91E42F330_06_IndexedFaceSet: THREE.Mesh;
    _000001E91E42F5D0_05_IndexedFaceSet001: THREE.Mesh;
    _000001E91E42F5D0_05_IndexedFaceSet001_1: THREE.Mesh;
    _000001E91E431160_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    ["_000001E91E42F1E0.001"]: THREE.MeshStandardMaterial;
    ["_000001E91E42F330_06.001"]: THREE.MeshStandardMaterial;
    ["_000001E91E42F5D0_05.001"]: THREE.MeshStandardMaterial;
    ["_000001E91E431160.001"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/HS-CENTRAL-PIT-STRUCTURE-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._000001E91E42F1E0_IndexedFaceSet.geometry} material={materials["_000001E91E42F1E0.001"]} />
      <mesh
        geometry={nodes._000001E91E42F330_06_IndexedFaceSet.geometry}
        material={materials["_000001E91E42F330_06.001"]}
      />
      <mesh geometry={nodes._000001E91E431160_IndexedFaceSet.geometry} material={materials["_000001E91E431160.001"]} />
      <mesh
        geometry={nodes._000001E91E42F5D0_05_IndexedFaceSet001.geometry}
        material={materials["_000001E91E42F5D0_05.001"]}
      />
      <mesh
        geometry={nodes._000001E91E42F5D0_05_IndexedFaceSet001_1.geometry}
        material={nodes._000001E91E42F5D0_05_IndexedFaceSet001_1.material}
      />
    </group>
  );
}

useGLTF.preload("/HS-CENTRAL-PIT-STRUCTURE-transformed.glb");
