/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/HS-CENTRAL-PIT-STRUCTURE-cut1.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _00000261A45EF460_IndexedFaceSet: THREE.Mesh;
    _00000261BAABE250_IndexedFaceSet001: THREE.Mesh;
    _00000261BAABE250_IndexedFaceSet001_1: THREE.Mesh;
    _00000261BAABEE20_IndexedFaceSet: THREE.Mesh;
    _00000261BAABF600_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    ["_00000261A45EF460.001"]: THREE.MeshStandardMaterial;
    ["_00000261BAABE250.001"]: THREE.MeshStandardMaterial;
    ["_00000261BAABEE20.001"]: THREE.MeshStandardMaterial;
    ["_00000261BAABF600.001"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/HS-CENTRAL-PIT-STRUCTURE-cut1-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._00000261A45EF460_IndexedFaceSet.geometry} material={materials["_00000261A45EF460.001"]} />
      <mesh geometry={nodes._00000261BAABEE20_IndexedFaceSet.geometry} material={materials["_00000261BAABEE20.001"]} />
      <mesh geometry={nodes._00000261BAABF600_IndexedFaceSet.geometry} material={materials["_00000261BAABF600.001"]} />
      <mesh
        geometry={nodes._00000261BAABE250_IndexedFaceSet001.geometry}
        material={materials["_00000261BAABE250.001"]}
      />
      <mesh
        geometry={nodes._00000261BAABE250_IndexedFaceSet001_1.geometry}
        material={nodes._00000261BAABE250_IndexedFaceSet001_1.material}
      />
    </group>
  );
}

useGLTF.preload("/HS-CENTRAL-PIT-STRUCTURE-cut1-transformed.glb");
