/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/HS-CENTRAL-PIT-STRUCTURE-cut2.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _000001E33418E1F0_IndexedFaceSet: THREE.Mesh;
    _000001E33418E490_17_IndexedFaceSet001: THREE.Mesh;
    _000001E33418E490_17_IndexedFaceSet001_1: THREE.Mesh;
    _000001E33FE7E180_IndexedFaceSet: THREE.Mesh;
    _000001E340F87560_014_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    ["_000001E33418E1F0.001"]: THREE.MeshStandardMaterial;
    ["_000001E33418E490_17.001"]: THREE.MeshStandardMaterial;
    ["_000001E33FE7E180.001"]: THREE.MeshStandardMaterial;
    ["_000001E340F87560_014.001"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/HS-CENTRAL-PIT-STRUCTURE-cut2-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._000001E33418E1F0_IndexedFaceSet.geometry} material={materials["_000001E33418E1F0.001"]} />
      <mesh geometry={nodes._000001E33FE7E180_IndexedFaceSet.geometry} material={materials["_000001E33FE7E180.001"]} />
      <mesh
        geometry={nodes._000001E340F87560_014_IndexedFaceSet.geometry}
        material={materials["_000001E340F87560_014.001"]}
      />
      <mesh
        geometry={nodes._000001E33418E490_17_IndexedFaceSet001.geometry}
        material={materials["_000001E33418E490_17.001"]}
      />
      <mesh
        geometry={nodes._000001E33418E490_17_IndexedFaceSet001_1.geometry}
        material={nodes._000001E33418E490_17_IndexedFaceSet001_1.material}
      />
    </group>
  );
}

useGLTF.preload("/HS-CENTRAL-PIT-STRUCTURE-cut2-transformed.glb");
