/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/HS-US-cut1.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _00000261A0F0F930_IndexedFaceSet001: THREE.Mesh;
    _00000261A0F0F930_IndexedFaceSet001_1: THREE.Mesh;
    _00000261A0F108F0_IndexedFaceSet001: THREE.Mesh;
    _00000261A0F108F0_IndexedFaceSet001_1: THREE.Mesh;
    _00000261B3AE9B30_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    ["_00000261A0F0F930.001"]: THREE.MeshStandardMaterial;
    ["_00000261A0F108F0.001"]: THREE.MeshStandardMaterial;
    ["_00000261B3AE9B30.001"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/HS-US-cut1-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._00000261B3AE9B30_IndexedFaceSet.geometry} material={materials["_00000261B3AE9B30.001"]} />
      <mesh
        geometry={nodes._00000261A0F0F930_IndexedFaceSet001.geometry}
        material={materials["_00000261A0F0F930.001"]}
      />
      <mesh
        geometry={nodes._00000261A0F0F930_IndexedFaceSet001_1.geometry}
        material={nodes._00000261A0F0F930_IndexedFaceSet001_1.material}
      />
      <mesh
        geometry={nodes._00000261A0F108F0_IndexedFaceSet001.geometry}
        material={materials["_00000261A0F108F0.001"]}
      />
      <mesh
        geometry={nodes._00000261A0F108F0_IndexedFaceSet001_1.geometry}
        material={nodes._00000261A0F108F0_IndexedFaceSet001_1.material}
      />
    </group>
  );
}

useGLTF.preload("/HS-US-cut1-transformed.glb");
