/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/HS-USA-cut1.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _000001E5BC442BF0_IndexedFaceSet: THREE.Mesh;
    _000001E5BCA52170_IndexedFaceSet001: THREE.Mesh;
    _000001E5BCA52170_IndexedFaceSet001_1: THREE.Mesh;
    _000001E5BCA52AA0_04_IndexedFaceSet001: THREE.Mesh;
    _000001E5BCA52AA0_04_IndexedFaceSet001_1: THREE.Mesh;
  };
  materials: {
    ["_000001E5BC442BF0.001"]: THREE.MeshStandardMaterial;
    ["_000001E5BCA52170.001"]: THREE.MeshStandardMaterial;
    ["_000001E5BCA52AA0_04.001"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/HS-USA-cut1-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._000001E5BC442BF0_IndexedFaceSet.geometry} material={materials["_000001E5BC442BF0.001"]} />
      <mesh
        geometry={nodes._000001E5BCA52170_IndexedFaceSet001.geometry}
        material={materials["_000001E5BCA52170.001"]}
      />
      <mesh
        geometry={nodes._000001E5BCA52170_IndexedFaceSet001_1.geometry}
        material={nodes._000001E5BCA52170_IndexedFaceSet001_1.material}
      />
      <mesh
        geometry={nodes._000001E5BCA52AA0_04_IndexedFaceSet001.geometry}
        material={materials["_000001E5BCA52AA0_04.001"]}
      />
      <mesh
        geometry={nodes._000001E5BCA52AA0_04_IndexedFaceSet001_1.geometry}
        material={nodes._000001E5BCA52AA0_04_IndexedFaceSet001_1.material}
      />
    </group>
  );
}

useGLTF.preload("/HS-USA-cut1-transformed.glb");
