/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/HS-US15-Serv-cut1.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Back: THREE.Mesh;
    Fan: THREE.Mesh;
    Cable: THREE.Mesh;
    Pipe: THREE.Mesh;
    Fire: THREE.Mesh;
    Racks: THREE.Mesh;
    Doors: THREE.Mesh;
    _000001C513B02840_IndexedFaceSet: THREE.Mesh;
    _000001C513B02840_IndexedFaceSet_1: THREE.Mesh;
    _000001C513B21470_IndexedFaceSet: THREE.Mesh;
    _000001C513B21470_IndexedFaceSet_1: THREE.Mesh;
  };
  materials: {
    _000001C58BCBEA70: THREE.MeshStandardMaterial;
    _000001C58BCBF4F0: THREE.MeshStandardMaterial;
    _000001C513B0D970: THREE.MeshStandardMaterial;
    _000001C513B126E0: THREE.MeshStandardMaterial;
    _000001C513B02450: THREE.MeshStandardMaterial;
    _000001C513B02840: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/HS-US15-Serv-cut1-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Back.geometry} material={materials._000001C58BCBEA70} />
      <mesh geometry={nodes.Fan.geometry} material={materials._000001C58BCBF4F0} />
      <mesh geometry={nodes.Cable.geometry} material={materials._000001C513B0D970} />
      <mesh geometry={nodes.Pipe.geometry} material={materials._000001C58BCBF4F0} />
      <mesh geometry={nodes.Fire.geometry} material={materials._000001C58BCBF4F0} />
      <mesh geometry={nodes.Racks.geometry} material={materials._000001C513B126E0} />
      <mesh geometry={nodes.Doors.geometry} material={materials._000001C513B02450} />
      <mesh geometry={nodes._000001C513B02840_IndexedFaceSet.geometry} material={materials._000001C513B02840} />
      <mesh
        geometry={nodes._000001C513B02840_IndexedFaceSet_1.geometry}
        material={nodes._000001C513B02840_IndexedFaceSet_1.material}
      />
      <mesh geometry={nodes._000001C513B21470_IndexedFaceSet.geometry} material={materials._000001C513B02450} />
      <mesh
        geometry={nodes._000001C513B21470_IndexedFaceSet_1.geometry}
        material={nodes._000001C513B21470_IndexedFaceSet_1.material}
      />
    </group>
  );
}

useGLTF.preload("/HS-US15-Serv-cut1-transformed.glb");
