/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/HS-US15-Serv-cut4.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Door001: THREE.Mesh;
    Pipe: THREE.Mesh;
    _000001DE1D224620_IndexedFaceSet: THREE.Mesh;
    _000001DE1D224620_IndexedFaceSet_1: THREE.Mesh;
    Cable: THREE.Mesh;
    Back: THREE.Mesh;
    Fire: THREE.Mesh;
    _000001DE1D2250A0_IndexedFaceSet: THREE.Mesh;
    _000001DE1D2250A0_IndexedFaceSet_1: THREE.Mesh;
    Vent: THREE.Mesh;
    Racks: THREE.Mesh;
  };
  materials: {
    _000001DE1D2240E0: THREE.MeshStandardMaterial;
    _000001DE1D2244D0: THREE.MeshStandardMaterial;
    _000001DE1D224620: THREE.MeshStandardMaterial;
    _000001DE1D2248C0: THREE.MeshStandardMaterial;
    _000001DE1D224CB0: THREE.MeshStandardMaterial;
    _000001DE1D2265A0: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/HS-US15-Serv-cut4-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Door001.geometry} material={materials._000001DE1D2240E0} />
      <mesh geometry={nodes.Pipe.geometry} material={materials._000001DE1D2244D0} />
      <mesh geometry={nodes.Cable.geometry} material={materials._000001DE1D2248C0} />
      <mesh geometry={nodes.Back.geometry} material={materials._000001DE1D224CB0} />
      <mesh geometry={nodes.Fire.geometry} material={materials._000001DE1D2244D0} />
      <mesh geometry={nodes.Vent.geometry} material={materials._000001DE1D2240E0} />
      <mesh geometry={nodes.Racks.geometry} material={materials._000001DE1D2265A0} />
      <mesh geometry={nodes._000001DE1D224620_IndexedFaceSet.geometry} material={materials._000001DE1D224620} />
      <mesh
        geometry={nodes._000001DE1D224620_IndexedFaceSet_1.geometry}
        material={nodes._000001DE1D224620_IndexedFaceSet_1.material}
      />
      <mesh geometry={nodes._000001DE1D2250A0_IndexedFaceSet.geometry} material={materials._000001DE1D2244D0} />
      <mesh
        geometry={nodes._000001DE1D2250A0_IndexedFaceSet_1.geometry}
        material={nodes._000001DE1D2250A0_IndexedFaceSet_1.material}
      />
    </group>
  );
}

useGLTF.preload("/HS-US15-Serv-cut4-transformed.glb");
