/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/HS-USA-Serv-cut2.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Pipe: THREE.Mesh;
    Door: THREE.Mesh;
    Fire: THREE.Mesh;
    Back: THREE.Mesh;
    Pump001: THREE.Mesh;
    Platform: THREE.Mesh;
    Racks: THREE.Mesh;
    Vent: THREE.Mesh;
    Cable: THREE.Mesh;
    Handrail001: THREE.Mesh;
    _00000207A7E8BBB0_IndexedFaceSet: THREE.Mesh;
    _00000207A7E8BBB0_IndexedFaceSet_1: THREE.Mesh;
    El_Box001: THREE.Mesh;
  };
  materials: {
    _00000207A7E72770: THREE.MeshStandardMaterial;
    _00000207A7E728C0: THREE.MeshStandardMaterial;
    _00000207A7E87CB0: THREE.MeshStandardMaterial;
    _00000207A7E88C70: THREE.MeshStandardMaterial;
    _00000207A7E896F0: THREE.MeshStandardMaterial;
    _00000207A7E89ED0: THREE.MeshStandardMaterial;
    _00000207A7E8BBB0: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/HS-USA-Serv-cut2-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Pipe.geometry} material={materials._00000207A7E72770} />
      <mesh geometry={nodes.Door.geometry} material={materials._00000207A7E728C0} />
      <mesh geometry={nodes.Fire.geometry} material={materials._00000207A7E72770} />
      <mesh geometry={nodes.Back.geometry} material={materials._00000207A7E87CB0} />
      <mesh geometry={nodes.Pump001.geometry} material={materials._00000207A7E72770} />
      <mesh geometry={nodes.Platform.geometry} material={materials._00000207A7E88C70} />
      <mesh geometry={nodes.Racks.geometry} material={materials._00000207A7E896F0} />
      <mesh geometry={nodes.Vent.geometry} material={materials._00000207A7E728C0} />
      <mesh geometry={nodes.Cable.geometry} material={materials._00000207A7E89ED0} />
      <mesh geometry={nodes.Handrail001.geometry} material={materials._00000207A7E896F0} />
      <mesh geometry={nodes.El_Box001.geometry} material={materials._00000207A7E896F0} />
      <mesh geometry={nodes._00000207A7E8BBB0_IndexedFaceSet.geometry} material={materials._00000207A7E8BBB0} />
      <mesh
        geometry={nodes._00000207A7E8BBB0_IndexedFaceSet_1.geometry}
        material={nodes._00000207A7E8BBB0_IndexedFaceSet_1.material}
      />
    </group>
  );
}

useGLTF.preload("/HS-USA-Serv-cut2-transformed.glb");
