/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Lar-Barrel-cut1.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0002: THREE.Mesh;
    Mesh_1002: THREE.Mesh;
    S__000001BC3EFE25A0: THREE.Mesh;
    S__000001BC3EFE25A0001: THREE.Mesh;
  };
  materials: {
    ["Material_0.017"]: THREE.MeshStandardMaterial;
    ["Material_1.013"]: THREE.MeshStandardMaterial;
    ["Material__000001BC3EFE25A0.002"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Lar-Barrel-cut1-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.S__000001BC3EFE25A0.geometry}
        material={materials["Material__000001BC3EFE25A0.002"]}
        position={[-2.83, 0, -2.98]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.S__000001BC3EFE25A0001.geometry}
        material={materials["Material__000001BC3EFE25A0.002"]}
        position={[0, -2.45, -2.85]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.Mesh_0002.geometry} material={materials["Material_0.017"]} />
      <mesh geometry={nodes.Mesh_1002.geometry} material={materials["Material_1.013"]} />
    </group>
  );
}

useGLTF.preload("/Lar-Barrel-cut1-transformed.glb");
