/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Lar-EMEC-SideC-cut2.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_1003: THREE.Mesh;
    Mesh_3004_1: THREE.Mesh;
    Mesh_3004_2: THREE.Mesh;
  };
  materials: {
    ["Material_1.002"]: THREE.MeshStandardMaterial;
    ["Material_3.004"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Lar-EMEC-SideC-cut2-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_1003.geometry} material={materials["Material_1.002"]} />
      <mesh geometry={nodes.Mesh_3004_1.geometry} material={materials["Material_3.004"]} />
      <mesh geometry={nodes.Mesh_3004_2.geometry} material={materials["Material_3.004"]} />
    </group>
  );
}

useGLTF.preload("/Lar-EMEC-SideC-cut2-transformed.glb");
