/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Lar-Barrel-cut2.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0005: THREE.Mesh;
    Mesh_2001: THREE.Mesh;
    Mesh_0003: THREE.Mesh;
  };
  materials: {
    ["Material_0.001"]: THREE.MeshStandardMaterial;
    ["Material_2.003"]: THREE.MeshStandardMaterial;
    ["Material_0.004"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Lar-Barrel-cut2-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0005.geometry} material={materials["Material_0.001"]} />
      <mesh geometry={nodes.Mesh_2001.geometry} material={materials["Material_2.003"]} />
      <mesh geometry={nodes.Mesh_0003.geometry} material={materials["Material_0.004"]} />
    </group>
  );
}

useGLTF.preload("/Lar-Barrel-cut2-transformed.glb");
