/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/MSPatchPannel-cut1.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _0000020950EC57A0_IndexedFaceSet: THREE.Mesh;
    _000002095112CDB0_IndexedFaceSet: THREE.Mesh;
    _00000209513C7820_0010_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    _0000020950EC57A0: THREE.MeshStandardMaterial;
    _000002095112CDB0: THREE.MeshStandardMaterial;
    _00000209513C7820_0010: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/MSPatchPannel-cut1-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._0000020950EC57A0_IndexedFaceSet.geometry} material={materials._0000020950EC57A0} />
      <mesh geometry={nodes._000002095112CDB0_IndexedFaceSet.geometry} material={materials._000002095112CDB0} />
      <mesh
        geometry={nodes._00000209513C7820_0010_IndexedFaceSet.geometry}
        material={materials._00000209513C7820_0010}
      />
    </group>
  );
}

useGLTF.preload("/MSPatchPannel-cut1-transformed.glb");
