/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/MSPatchPannel-cut2.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _000001DAB0540550_IndexedFaceSet: THREE.Mesh;
    _000001DAB29A83A0_IndexedFaceSet: THREE.Mesh;
    _000001DAB3976F40_01_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    _000001DAB0540550: THREE.MeshStandardMaterial;
    _000001DAB29A83A0: THREE.MeshStandardMaterial;
    _000001DAB3976F40_01: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/MSPatchPannel-cut2-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._000001DAB0540550_IndexedFaceSet.geometry} material={materials._000001DAB0540550} />
      <mesh geometry={nodes._000001DAB29A83A0_IndexedFaceSet.geometry} material={materials._000001DAB29A83A0} />
      <mesh geometry={nodes._000001DAB3976F40_01_IndexedFaceSet.geometry} material={materials._000001DAB3976F40_01} />
    </group>
  );
}

useGLTF.preload("/MSPatchPannel-cut2-transformed.glb");
