/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/MSPatchPannel-cut3.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _00000191ACF0A1B0_IndexedFaceSet: THREE.Mesh;
    _00000191ACF0A450_04_IndexedFaceSet: THREE.Mesh;
    _00000191ACF0C3D0_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    _00000191ACF0A1B0: THREE.MeshStandardMaterial;
    _00000191ACF0A450_04: THREE.MeshStandardMaterial;
    _00000191ACF0C3D0: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/MSPatchPannel-cut3-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._00000191ACF0A1B0_IndexedFaceSet.geometry} material={materials._00000191ACF0A1B0} />
      <mesh geometry={nodes._00000191ACF0A450_04_IndexedFaceSet.geometry} material={materials._00000191ACF0A450_04} />
      <mesh geometry={nodes._00000191ACF0C3D0_IndexedFaceSet.geometry} material={materials._00000191ACF0C3D0} />
    </group>
  );
}

useGLTF.preload("/MSPatchPannel-cut3-transformed.glb");
