/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/MSPatchPannel-cut4.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _0000020780176150_IndexedFaceSet: THREE.Mesh;
    _00000207802A7C40_IndexedFaceSet: THREE.Mesh;
    _00000207802AF3B0_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    _0000020780176150: THREE.MeshStandardMaterial;
    _00000207802A7C40: THREE.MeshStandardMaterial;
    _00000207802AF3B0: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/MSPatchPannel-cut4-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._0000020780176150_IndexedFaceSet.geometry} material={materials._0000020780176150} />
      <mesh geometry={nodes._00000207802A7C40_IndexedFaceSet.geometry} material={materials._00000207802A7C40} />
      <mesh geometry={nodes._00000207802AF3B0_IndexedFaceSet.geometry} material={materials._00000207802AF3B0} />
    </group>
  );
}

useGLTF.preload("/MSPatchPannel-cut4-transformed.glb");
