/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Muon-Barrel-Inner-cut3.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_1: THREE.Mesh;
    Mesh_2: THREE.Mesh;
    Mesh_4: THREE.Mesh;
    Mesh_5: THREE.Mesh;
  };
  materials: {
    ["Material_1.024"]: THREE.MeshStandardMaterial;
    Material_4: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Muon-Barrel-Inner-cut3-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_1.geometry} material={materials["Material_1.024"]} />
      <mesh geometry={nodes.Mesh_2.geometry} material={materials["Material_1.024"]} />
      <mesh geometry={nodes.Mesh_4.geometry} material={materials.Material_4} />
      <mesh geometry={nodes.Mesh_5.geometry} material={materials.Material_4} />
    </group>
  );
}

useGLTF.preload("/Muon-Barrel-Inner-cut3-transformed.glb");
