/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Muon-Barrel-Outer.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0008: THREE.Mesh;
    Mesh_1006: THREE.Mesh;
  };
  materials: {
    ["Material_0.045"]: THREE.MeshStandardMaterial;
    ["Material_1.028"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Muon-Barrel-Outer-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0008.geometry} material={materials["Material_0.045"]} />
      <mesh geometry={nodes.Mesh_1006.geometry} material={materials["Material_1.028"]} />
    </group>
  );
}

useGLTF.preload("/Muon-Barrel-Outer-transformed.glb");
