/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Muon-Big-Wheel-MDT-SideC-cut1.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0003: THREE.Mesh;
    Mesh_1003: THREE.Mesh;
    S__000001BC3EFE25A0: THREE.Mesh;
  };
  materials: {
    ["Material_0.053"]: THREE.MeshStandardMaterial;
    ["Material_1.035"]: THREE.MeshStandardMaterial;
    ["Material__000001BC3EFE25A0.008"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Muon-Big-Wheel-MDT-SideC-cut1-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 0, Math.PI]}>
        <mesh geometry={nodes.Mesh_0003.geometry} material={materials["Material_0.053"]} />
        <mesh geometry={nodes.Mesh_1003.geometry} material={materials["Material_1.035"]} />
      </group>
      <mesh
        geometry={nodes.S__000001BC3EFE25A0.geometry}
        material={materials["Material__000001BC3EFE25A0.008"]}
        position={[2.63, -11.36, -14.06]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[-1, 1, 1]}
      />
    </group>
  );
}

useGLTF.preload("/Muon-Big-Wheel-MDT-SideC-cut1-transformed.glb");
