/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Muon-Barrel-Outer-cut1.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0009: THREE.Mesh;
    Mesh_2009: THREE.Mesh;
  };
  materials: {
    ["Material_0.046"]: THREE.MeshStandardMaterial;
    ["Material_2.014"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Muon-Barrel-Outer-cut1-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0009.geometry} material={materials["Material_0.046"]} />
      <mesh geometry={nodes.Mesh_2009.geometry} material={materials["Material_2.014"]} />
    </group>
  );
}

useGLTF.preload("/Muon-Barrel-Outer-cut1-transformed.glb");
