/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Muon-Big-Wheel-MDT-SideA-cut3.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    S__2D0B1468: THREE.Mesh;
    S__2FBDB868: THREE.Mesh;
  };
  materials: {
    Material__2D0B1468: THREE.MeshStandardMaterial;
    Material__2FBDB868: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Muon-Big-Wheel-MDT-SideA-cut3-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.S__2D0B1468.geometry}
        material={materials.Material__2D0B1468}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.S__2FBDB868.geometry}
        material={materials.Material__2FBDB868}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/Muon-Big-Wheel-MDT-SideA-cut3-transformed.glb");
