/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Muon-Barrel-Middle-cut3.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_1004: THREE.Mesh;
    Mesh_4003: THREE.Mesh;
    Mesh_5003: THREE.Mesh;
    Mesh_6001: THREE.Mesh;
  };
  materials: {
    ["Material_1.027"]: THREE.MeshStandardMaterial;
    ["Material_4.015"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Muon-Barrel-Middle-cut3-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_1004.geometry} material={materials["Material_1.027"]} />
      <mesh geometry={nodes.Mesh_4003.geometry} material={materials["Material_4.015"]} />
      <mesh geometry={nodes.Mesh_5003.geometry} material={materials["Material_4.015"]} />
      <mesh geometry={nodes.Mesh_6001.geometry} material={materials["Material_1.027"]} />
    </group>
  );
}

useGLTF.preload("/Muon-Barrel-Middle-cut3-transformed.glb");
