/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Muon-Big-Wheel-MDT-SideA.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0010: THREE.Mesh;
    Mesh_1010: THREE.Mesh;
  };
  materials: {
    ["Material_0.051"]: THREE.MeshStandardMaterial;
    ["Material_1.033"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Muon-Big-Wheel-MDT-SideA-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 0, Math.PI]}>
        <mesh geometry={nodes.Mesh_0010.geometry} material={materials["Material_0.051"]} />
        <mesh geometry={nodes.Mesh_1010.geometry} material={materials["Material_1.033"]} />
      </group>
    </group>
  );
}

useGLTF.preload("/Muon-Big-Wheel-MDT-SideA-transformed.glb");
