/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Muon-Barrel-Inner-cut1.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_1002: THREE.Mesh;
    Mesh_2002: THREE.Mesh;
    Mesh_4002: THREE.Mesh;
    Mesh_5002: THREE.Mesh;
  };
  materials: {
    ["Material_1.022"]: THREE.MeshStandardMaterial;
    ["Material_4.011"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Muon-Barrel-Inner-cut1-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_1002.geometry} material={materials["Material_1.022"]} />
      <mesh geometry={nodes.Mesh_2002.geometry} material={materials["Material_1.022"]} />
      <mesh geometry={nodes.Mesh_4002.geometry} material={materials["Material_4.011"]} />
      <mesh geometry={nodes.Mesh_5002.geometry} material={materials["Material_4.011"]} />
    </group>
  );
}

useGLTF.preload("/Muon-Barrel-Inner-cut1-transformed.glb");
