/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Muon-Barrel-Middle.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0002: THREE.Mesh;
    Mesh_2001: THREE.Mesh;
  };
  materials: {
    ["Material_0.044"]: THREE.MeshStandardMaterial;
    ["Material_2.013"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Muon-Barrel-Middle-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0002.geometry} material={materials["Material_0.044"]} />
      <mesh geometry={nodes.Mesh_2001.geometry} material={materials["Material_2.013"]} />
    </group>
  );
}

useGLTF.preload("/Muon-Barrel-Middle-transformed.glb");
