/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Muon-Barrel-Middle-cut1.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_1002: THREE.Mesh;
    Mesh_3001: THREE.Mesh;
    Mesh_4001: THREE.Mesh;
    Mesh_6: THREE.Mesh;
  };
  materials: {
    ["Material_1.025"]: THREE.MeshStandardMaterial;
    ["Material_3.009"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Muon-Barrel-Middle-cut1-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_1002.geometry} material={materials["Material_1.025"]} />
      <mesh geometry={nodes.Mesh_3001.geometry} material={materials["Material_3.009"]} />
      <mesh geometry={nodes.Mesh_4001.geometry} material={materials["Material_3.009"]} />
      <mesh geometry={nodes.Mesh_6.geometry} material={materials["Material_1.025"]} />
    </group>
  );
}

useGLTF.preload("/Muon-Barrel-Middle-cut1-transformed.glb");
