/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Muon-Barrel-Middle-cut2.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_1005: THREE.Mesh;
    Mesh_3003: THREE.Mesh;
    Mesh_4004: THREE.Mesh;
    Mesh_5004: THREE.Mesh;
  };
  materials: {
    ["Material_1.026"]: THREE.MeshStandardMaterial;
    ["Material_4.014"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Muon-Barrel-Middle-cut2-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_1005.geometry} material={materials["Material_1.026"]} />
      <mesh geometry={nodes.Mesh_3003.geometry} material={materials["Material_1.026"]} />
      <mesh geometry={nodes.Mesh_4004.geometry} material={materials["Material_4.014"]} />
      <mesh geometry={nodes.Mesh_5004.geometry} material={materials["Material_4.014"]} />
    </group>
  );
}

useGLTF.preload("/Muon-Barrel-Middle-cut2-transformed.glb");
