/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Outer-Wheel-SideA-cut3.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0008: THREE.Mesh;
    Mesh_1008: THREE.Mesh;
  };
  materials: {
    ["Material_0.057"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Outer-Wheel-SideA-cut3-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0008.geometry} material={materials["Material_0.057"]} />
      <mesh geometry={nodes.Mesh_1008.geometry} material={materials["Material_0.057"]} />
    </group>
  );
}

useGLTF.preload("/Outer-Wheel-SideA-cut3-transformed.glb");
