/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Pixel-cut4.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["S_Mesh_1-045"]: THREE.Mesh;
    ["S_Mesh_2-016"]: THREE.Mesh;
    ["S_Mesh_2-018"]: THREE.Mesh;
    ["S_Mesh_4-015"]: THREE.Mesh;
    ["S_Mesh_5-010"]: THREE.Mesh;
  };
  materials: {
    ["Material_Mesh_1-045.001"]: THREE.MeshStandardMaterial;
    ["Material_Mesh_2-016.001"]: THREE.MeshStandardMaterial;
    ["Material_Mesh_2-018.001"]: THREE.MeshStandardMaterial;
    ["Material_Mesh_4-015.001"]: THREE.MeshStandardMaterial;
    ["Material_Mesh_5-010.001"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Pixel-cut4-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["S_Mesh_1-045"].geometry}
        material={materials["Material_Mesh_1-045.001"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S_Mesh_2-016"].geometry}
        material={materials["Material_Mesh_2-016.001"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S_Mesh_2-018"].geometry}
        material={materials["Material_Mesh_2-018.001"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S_Mesh_4-015"].geometry}
        material={materials["Material_Mesh_4-015.001"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S_Mesh_5-010"].geometry}
        material={materials["Material_Mesh_5-010.001"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/Pixel-cut4-transformed.glb");
