/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Pixel.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0: THREE.Mesh;
    Mesh_1: THREE.Mesh;
    Mesh_2: THREE.Mesh;
    Mesh_3: THREE.Mesh;
    Mesh_4: THREE.Mesh;
  };
  materials: {
    ["Material_0.062"]: THREE.MeshStandardMaterial;
    ["Material_1.044"]: THREE.MeshStandardMaterial;
    ["Material_2.015"]: THREE.MeshStandardMaterial;
    ["Material_3.011"]: THREE.MeshStandardMaterial;
    ["Material_4.016"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Pixel-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0.geometry} material={materials["Material_0.062"]} />
      <mesh geometry={nodes.Mesh_1.geometry} material={materials["Material_1.044"]} />
      <mesh geometry={nodes.Mesh_2.geometry} material={materials["Material_2.015"]} />
      <mesh geometry={nodes.Mesh_3.geometry} material={materials["Material_3.011"]} />
      <mesh geometry={nodes.Mesh_4.geometry} material={materials["Material_4.016"]} />
    </group>
  );
}

useGLTF.preload("/Pixel-transformed.glb");
