/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/pixel-pp1-side-A-cut2.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _000001AD17D66EC0_IndexedFaceSet003: THREE.Mesh;
    _000001AD17D66EC0_IndexedFaceSet003_1: THREE.Mesh;
    _000001AD17D6CAA0_IndexedFaceSet: THREE.Mesh;
    _000001AD282AEEB0_IndexedFaceSet: THREE.Mesh;
    _000001AD282B4010_IndexedFaceSet: THREE.Mesh;
    _000001AD285BD460_001_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    ["_000001AD17D66EC0.003"]: THREE.MeshStandardMaterial;
    ["_000001AD17D6CAA0.003"]: THREE.MeshStandardMaterial;
    ["_000001AD282AEEB0.003"]: THREE.MeshStandardMaterial;
    ["_000001AD285BD460_001.003"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/pixel-pp1-side-A-cut2-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._000001AD17D6CAA0_IndexedFaceSet.geometry} material={materials["_000001AD17D6CAA0.003"]} />
      <mesh geometry={nodes._000001AD282AEEB0_IndexedFaceSet.geometry} material={materials["_000001AD282AEEB0.003"]} />
      <mesh geometry={nodes._000001AD282B4010_IndexedFaceSet.geometry} material={materials["_000001AD282AEEB0.003"]} />
      <mesh
        geometry={nodes._000001AD285BD460_001_IndexedFaceSet.geometry}
        material={materials["_000001AD285BD460_001.003"]}
      />
      <mesh
        geometry={nodes._000001AD17D66EC0_IndexedFaceSet003.geometry}
        material={materials["_000001AD17D66EC0.003"]}
      />
      <mesh
        geometry={nodes._000001AD17D66EC0_IndexedFaceSet003_1.geometry}
        material={nodes._000001AD17D66EC0_IndexedFaceSet003_1.material}
      />
    </group>
  );
}

useGLTF.preload("/pixel-pp1-side-A-cut2-transformed.glb");
