/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Pixel-cut1.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_2001: THREE.Mesh;
    Mesh_3001: THREE.Mesh;
    Mesh_4001: THREE.Mesh;
    Mesh_5: THREE.Mesh;
    Mesh_6: THREE.Mesh;
  };
  materials: {
    ["Material_2.016"]: THREE.MeshStandardMaterial;
    ["Material_3.012"]: THREE.MeshStandardMaterial;
    ["Material_4.017"]: THREE.MeshStandardMaterial;
    ["Material_5.013"]: THREE.MeshStandardMaterial;
    ["Material_6.002"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Pixel-cut1-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_2001.geometry} material={materials["Material_2.016"]} />
      <mesh geometry={nodes.Mesh_3001.geometry} material={materials["Material_3.012"]} />
      <mesh geometry={nodes.Mesh_4001.geometry} material={materials["Material_4.017"]} />
      <mesh geometry={nodes.Mesh_5.geometry} material={materials["Material_5.013"]} />
      <mesh geometry={nodes.Mesh_6.geometry} material={materials["Material_6.002"]} />
    </group>
  );
}

useGLTF.preload("/Pixel-cut1-transformed.glb");
