/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/pixel-pp1-side-A-cut4.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _000001DDF3269450_IndexedFaceSet: THREE.Mesh;
    _000001DDF34AD2E0_IndexedFaceSet002: THREE.Mesh;
    _000001DDF34AD2E0_IndexedFaceSet002_1: THREE.Mesh;
    _000001DDF383E5D0_IndexedFaceSet: THREE.Mesh;
    _000001DDF3840160_IndexedFaceSet: THREE.Mesh;
    _000001DDF3EE45C0_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    ["_000001DDF3269450.002"]: THREE.MeshStandardMaterial;
    ["_000001DDF34AD2E0.002"]: THREE.MeshStandardMaterial;
    ["_000001DDF383E5D0.002"]: THREE.MeshStandardMaterial;
    ["_000001DDF3EE45C0.002"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/pixel-pp1-side-A-cut4-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._000001DDF3269450_IndexedFaceSet.geometry} material={materials["_000001DDF3269450.002"]} />
      <mesh geometry={nodes._000001DDF383E5D0_IndexedFaceSet.geometry} material={materials["_000001DDF383E5D0.002"]} />
      <mesh geometry={nodes._000001DDF3840160_IndexedFaceSet.geometry} material={materials["_000001DDF383E5D0.002"]} />
      <mesh geometry={nodes._000001DDF3EE45C0_IndexedFaceSet.geometry} material={materials["_000001DDF3EE45C0.002"]} />
      <mesh
        geometry={nodes._000001DDF34AD2E0_IndexedFaceSet002.geometry}
        material={materials["_000001DDF34AD2E0.002"]}
      />
      <mesh
        geometry={nodes._000001DDF34AD2E0_IndexedFaceSet002_1.geometry}
        material={nodes._000001DDF34AD2E0_IndexedFaceSet002_1.material}
      />
    </group>
  );
}

useGLTF.preload("/pixel-pp1-side-A-cut4-transformed.glb");
