/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/QA-Magnets-cut3.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["S_Mesh_1-109"]: THREE.Mesh;
    ["S_Mesh_1-110"]: THREE.Mesh;
    ["S_Mesh_2-062"]: THREE.Mesh;
    ["S_Mesh_3-037"]: THREE.Mesh;
    ["S_Mesh_4-029"]: THREE.Mesh;
    ["S_Mesh_5-015"]: THREE.Mesh;
    ["S__0469C088-001"]: THREE.Mesh;
    ["S__046A9078-001"]: THREE.Mesh;
    ["S__047E7608-001"]: THREE.Mesh;
    ["S__04CB5DB8-001"]: THREE.Mesh;
    ["S__04CC2A58-001"]: THREE.Mesh;
  };
  materials: {
    ["Material_Mesh_1-109"]: THREE.MeshStandardMaterial;
    ["Material_Mesh_1-110"]: THREE.MeshStandardMaterial;
    ["Material_Mesh_2-062"]: THREE.MeshStandardMaterial;
    ["Material_Mesh_3-037"]: THREE.MeshStandardMaterial;
    ["Material_Mesh_4-029"]: THREE.MeshStandardMaterial;
    ["Material_Mesh_5-015"]: THREE.MeshStandardMaterial;
    ["Material__0469C088-001"]: THREE.MeshStandardMaterial;
    ["Material__046A9078-001"]: THREE.MeshStandardMaterial;
    ["Material__04CB5DB8-001"]: THREE.MeshStandardMaterial;
    ["Material__04CC2A58-001"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/QA-Magnets-cut3-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["S_Mesh_1-109"].geometry}
        material={materials["Material_Mesh_1-109"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S_Mesh_1-110"].geometry}
        material={materials["Material_Mesh_1-110"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S_Mesh_2-062"].geometry}
        material={materials["Material_Mesh_2-062"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S_Mesh_3-037"].geometry}
        material={materials["Material_Mesh_3-037"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S_Mesh_4-029"].geometry}
        material={materials["Material_Mesh_4-029"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S_Mesh_5-015"].geometry}
        material={materials["Material_Mesh_5-015"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S__0469C088-001"].geometry}
        material={materials["Material__0469C088-001"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S__046A9078-001"].geometry}
        material={materials["Material__046A9078-001"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S__047E7608-001"].geometry}
        material={materials["Material_Mesh_4-029"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S__04CB5DB8-001"].geometry}
        material={materials["Material__04CB5DB8-001"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S__04CC2A58-001"].geometry}
        material={materials["Material__04CC2A58-001"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/QA-Magnets-cut3-transformed.glb");
