/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/SCT-SideA-cut2.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0015: THREE.Mesh;
    Mesh_1015: THREE.Mesh;
    Mesh_2016: THREE.Mesh;
    Mesh_3010: THREE.Mesh;
    Mesh_4005: THREE.Mesh;
  };
  materials: {
    ["Material_0.079"]: THREE.MeshStandardMaterial;
    ["Material_1.052"]: THREE.MeshStandardMaterial;
    ["Material_2.024"]: THREE.MeshStandardMaterial;
    ["Material_3.018"]: THREE.MeshStandardMaterial;
    ["Material_4.021"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/SCT-SideA-cut2-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0015.geometry} material={materials["Material_0.079"]} />
      <mesh geometry={nodes.Mesh_1015.geometry} material={materials["Material_1.052"]} />
      <mesh geometry={nodes.Mesh_2016.geometry} material={materials["Material_2.024"]} />
      <mesh geometry={nodes.Mesh_3010.geometry} material={materials["Material_3.018"]} />
      <mesh geometry={nodes.Mesh_4005.geometry} material={materials["Material_4.021"]} />
    </group>
  );
}

useGLTF.preload("/SCT-SideA-cut2-transformed.glb");
