/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/SCT-BAR-cut1.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0006: THREE.Mesh;
    Mesh_1006: THREE.Mesh;
    Mesh_2006: THREE.Mesh;
  };
  materials: {
    ["Material_0.077"]: THREE.MeshStandardMaterial;
    ["Material_1.050"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/SCT-BAR-cut1-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0006.geometry} material={materials["Material_0.077"]} />
      <mesh geometry={nodes.Mesh_1006.geometry} material={materials["Material_1.050"]} />
      <mesh geometry={nodes.Mesh_2006.geometry} material={materials["Material_1.050"]} />
    </group>
  );
}

useGLTF.preload("/SCT-BAR-cut1-transformed.glb");
