/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/SCT-BAR-cut3.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_2011: THREE.Mesh;
    Mesh_3008: THREE.Mesh;
  };
  materials: {
    ["Material_2.022"]: THREE.MeshStandardMaterial;
    ["Material_3.016"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/SCT-BAR-cut3-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_2011.geometry} material={materials["Material_2.022"]} />
      <mesh geometry={nodes.Mesh_3008.geometry} material={materials["Material_3.016"]} />
    </group>
  );
}

useGLTF.preload("/SCT-BAR-cut3-transformed.glb");
