/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/SCT-BAR-cut2.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_2008: THREE.Mesh;
    Mesh_3005: THREE.Mesh;
  };
  materials: {
    ["Material_2.021"]: THREE.MeshStandardMaterial;
    ["Material_3.015"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/SCT-BAR-cut2-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_2008.geometry} material={materials["Material_2.021"]} />
      <mesh geometry={nodes.Mesh_3005.geometry} material={materials["Material_3.015"]} />
    </group>
  );
}

useGLTF.preload("/SCT-BAR-cut2-transformed.glb");
