/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/SCT-SideA.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0014: THREE.Mesh;
    Mesh_1014: THREE.Mesh;
    Mesh_2015: THREE.Mesh;
    Mesh_3009: THREE.Mesh;
    Mesh_4004: THREE.Mesh;
  };
  materials: {
    ["Material_0.078"]: THREE.MeshStandardMaterial;
    ["Material_1.051"]: THREE.MeshStandardMaterial;
    ["Material_2.023"]: THREE.MeshStandardMaterial;
    ["Material_3.017"]: THREE.MeshStandardMaterial;
    ["Material_4.020"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/SCT-SideA-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0014.geometry} material={materials["Material_0.078"]} />
      <mesh geometry={nodes.Mesh_1014.geometry} material={materials["Material_1.051"]} />
      <mesh geometry={nodes.Mesh_2015.geometry} material={materials["Material_2.023"]} />
      <mesh geometry={nodes.Mesh_3009.geometry} material={materials["Material_3.017"]} />
      <mesh geometry={nodes.Mesh_4004.geometry} material={materials["Material_4.020"]} />
    </group>
  );
}

useGLTF.preload("/SCT-SideA-transformed.glb");
