/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/SCT-BAR.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_1005: THREE.Mesh;
    Mesh_2005: THREE.Mesh;
    Mesh_0013: THREE.Mesh;
  };
  materials: {
    ["Material_1.049"]: THREE.MeshStandardMaterial;
    ["Material_0.076"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/SCT-BAR-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0013.geometry} material={materials["Material_0.076"]} />
      <mesh geometry={nodes.Mesh_1005.geometry} material={materials["Material_1.049"]} />
      <mesh geometry={nodes.Mesh_2005.geometry} material={materials["Material_1.049"]} />
    </group>
  );
}

useGLTF.preload("/SCT-BAR-transformed.glb");
