/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/SCT-SideC-cut2.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0004: THREE.Mesh;
    Mesh_1004: THREE.Mesh;
    Mesh_2004: THREE.Mesh;
    Mesh_3004: THREE.Mesh;
    Mesh_4004: THREE.Mesh;
  };
  materials: {
    ["Material_0.083"]: THREE.MeshStandardMaterial;
    ["Material_1.056"]: THREE.MeshStandardMaterial;
    ["Material_2.028"]: THREE.MeshStandardMaterial;
    ["Material_3.022"]: THREE.MeshStandardMaterial;
    ["Material_4.025"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/SCT-SideC-cut2-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0004.geometry} material={materials["Material_0.083"]} />
      <mesh geometry={nodes.Mesh_1004.geometry} material={materials["Material_1.056"]} />
      <mesh geometry={nodes.Mesh_2004.geometry} material={materials["Material_2.028"]} />
      <mesh geometry={nodes.Mesh_3004.geometry} material={materials["Material_3.022"]} />
      <mesh geometry={nodes.Mesh_4004.geometry} material={materials["Material_4.025"]} />
    </group>
  );
}

useGLTF.preload("/SCT-SideC-cut2-transformed.glb");
