/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Serv-Muon-SW-cut4.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _000002AC2C6C39E0_IndexedFaceSet: THREE.Mesh;
    _000002AC2C6C9860_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    ["Material.038"]: THREE.MeshStandardMaterial;
    ["Material.039"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Serv-Muon-SW-cut4-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._000002AC2C6C39E0_IndexedFaceSet.geometry} material={materials["Material.038"]} />
      <mesh geometry={nodes._000002AC2C6C9860_IndexedFaceSet.geometry} material={materials["Material.039"]} />
    </group>
  );
}

useGLTF.preload("/Serv-Muon-SW-cut4-transformed.glb");
