/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Serv-Z0-Sec9-cut2.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _0000021323C12A20_IndexedFaceSet: THREE.Mesh;
    _0000021323C14070_IndexedFaceSet: THREE.Mesh;
    _0000021323C16D10_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    _0000021323C12A20: THREE.MeshStandardMaterial;
    _0000021323C14070: THREE.MeshStandardMaterial;
    _0000021323C16D10: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Serv-Z0-Sec9-cut2-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._0000021323C12A20_IndexedFaceSet.geometry} material={materials._0000021323C12A20} />
      <mesh geometry={nodes._0000021323C14070_IndexedFaceSet.geometry} material={materials._0000021323C14070} />
      <mesh geometry={nodes._0000021323C16D10_IndexedFaceSet.geometry} material={materials._0000021323C16D10} />
    </group>
  );
}

useGLTF.preload("/Serv-Z0-Sec9-cut2-transformed.glb");
