/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Serv-Z0-Sec15-cut4.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _000002DE5EB405A0_IndexedFaceSet: THREE.Mesh;
    _000002DE5EB42E50_IndexedFaceSet: THREE.Mesh;
    _000002DE5EB47140_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    ["Material.022"]: THREE.MeshStandardMaterial;
    ["Material.021"]: THREE.MeshStandardMaterial;
    ["Material.023"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Serv-Z0-Sec15-cut4-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._000002DE5EB405A0_IndexedFaceSet.geometry} material={materials["Material.022"]} />
      <mesh geometry={nodes._000002DE5EB42E50_IndexedFaceSet.geometry} material={materials["Material.021"]} />
      <mesh geometry={nodes._000002DE5EB47140_IndexedFaceSet.geometry} material={materials["Material.023"]} />
    </group>
  );
}

useGLTF.preload("/Serv-Z0-Sec15-cut4-transformed.glb");
