/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Serv-Z0-Sec11.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _000002DE3571F310_IndexedFaceSet: THREE.Mesh;
    _000002DE3571F9A0_IndexedFaceSet: THREE.Mesh;
    _000002DE52A13470_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    ["Material.009"]: THREE.MeshStandardMaterial;
    ["Material.010"]: THREE.MeshStandardMaterial;
    ["Material.011"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Serv-Z0-Sec11-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._000002DE3571F310_IndexedFaceSet.geometry} material={materials["Material.009"]} />
      <mesh geometry={nodes._000002DE3571F9A0_IndexedFaceSet.geometry} material={materials["Material.010"]} />
      <mesh geometry={nodes._000002DE52A13470_IndexedFaceSet.geometry} material={materials["Material.011"]} />
    </group>
  );
}

useGLTF.preload("/Serv-Z0-Sec11-transformed.glb");
