/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Serv-Muon-SW.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _000002AC1989FCB0_IndexedFaceSet: THREE.Mesh;
    _000002AC365E59F0_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    ["Material.027"]: THREE.MeshStandardMaterial;
    ["Material.028"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Serv-Muon-SW-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._000002AC1989FCB0_IndexedFaceSet.geometry} material={materials["Material.027"]} />
      <mesh geometry={nodes._000002AC365E59F0_IndexedFaceSet.geometry} material={materials["Material.028"]} />
    </group>
  );
}

useGLTF.preload("/Serv-Muon-SW-transformed.glb");
