/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Serv-Z0-Sec1.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _0000021323C13F20_IndexedFaceSet: THREE.Mesh;
    _0000021323C15960_IndexedFaceSet: THREE.Mesh;
    _0000021323C17100_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    ["_0000021323C13F20.001"]: THREE.MeshStandardMaterial;
    ["_0000021323C15960.001"]: THREE.MeshStandardMaterial;
    ["_0000021323C17100.001"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Serv-Z0-Sec1-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._0000021323C13F20_IndexedFaceSet.geometry} material={materials["_0000021323C13F20.001"]} />
      <mesh geometry={nodes._0000021323C15960_IndexedFaceSet.geometry} material={materials["_0000021323C15960.001"]} />
      <mesh geometry={nodes._0000021323C17100_IndexedFaceSet.geometry} material={materials["_0000021323C17100.001"]} />
    </group>
  );
}

useGLTF.preload("/Serv-Z0-Sec1-transformed.glb");
