/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Serv-Z0-Sec11-cut2.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _000001F629763E20_IndexedFaceSet: THREE.Mesh;
    _000001F6297666D0_IndexedFaceSet: THREE.Mesh;
    _000001F62976A870_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    ["Material.016"]: THREE.MeshStandardMaterial;
    ["Material.017"]: THREE.MeshStandardMaterial;
    ["Material.015"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Serv-Z0-Sec11-cut2-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._000001F629763E20_IndexedFaceSet.geometry} material={materials["Material.016"]} />
      <mesh geometry={nodes._000001F6297666D0_IndexedFaceSet.geometry} material={materials["Material.017"]} />
      <mesh geometry={nodes._000001F62976A870_IndexedFaceSet.geometry} material={materials["Material.015"]} />
    </group>
  );
}

useGLTF.preload("/Serv-Z0-Sec11-cut2-transformed.glb");
