/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Serv-Z0-Sec5.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _000002130905C090_IndexedFaceSet: THREE.Mesh;
    _0000021331026BE0_IndexedFaceSet: THREE.Mesh;
    _0000021331026BE0_004_IndexedFaceSet: THREE.Mesh;
    _0000021331053880_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    _000002130905C090: THREE.MeshStandardMaterial;
    _0000021331026BE0: THREE.MeshStandardMaterial;
    _0000021331026BE0_004: THREE.MeshStandardMaterial;
    _0000021331053880: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Serv-Z0-Sec5-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._000002130905C090_IndexedFaceSet.geometry} material={materials._000002130905C090} />
      <mesh geometry={nodes._0000021331026BE0_IndexedFaceSet.geometry} material={materials._0000021331026BE0} />
      <mesh geometry={nodes._0000021331026BE0_004_IndexedFaceSet.geometry} material={materials._0000021331026BE0_004} />
      <mesh geometry={nodes._0000021331053880_IndexedFaceSet.geometry} material={materials._0000021331053880} />
    </group>
  );
}

useGLTF.preload("/Serv-Z0-Sec5-transformed.glb");
