/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Serv-Z0-Sec15-cut1.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _0000029B2A5E0490_IndexedFaceSet: THREE.Mesh;
    _0000029B2A5E8A70_IndexedFaceSet: THREE.Mesh;
    _0000029B2D602010_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    ["Material.025"]: THREE.MeshStandardMaterial;
    ["Material.026"]: THREE.MeshStandardMaterial;
    ["Material.024"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Serv-Z0-Sec15-cut1-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._0000029B2A5E0490_IndexedFaceSet.geometry} material={materials["Material.025"]} />
      <mesh geometry={nodes._0000029B2A5E8A70_IndexedFaceSet.geometry} material={materials["Material.026"]} />
      <mesh geometry={nodes._0000029B2D602010_IndexedFaceSet.geometry} material={materials["Material.024"]} />
    </group>
  );
}

useGLTF.preload("/Serv-Z0-Sec15-cut1-transformed.glb");
