/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Serv-Z0-Sec3.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _0000021323C0D770_IndexedFaceSet: THREE.Mesh;
    _0000021323C0DA10_IndexedFaceSet: THREE.Mesh;
    _0000021323C0EC70_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    _0000021323C0D770: THREE.MeshStandardMaterial;
    _0000021323C0DA10: THREE.MeshStandardMaterial;
    _0000021323C0EC70: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Serv-Z0-Sec3-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._0000021323C0D770_IndexedFaceSet.geometry} material={materials._0000021323C0D770} />
      <mesh geometry={nodes._0000021323C0DA10_IndexedFaceSet.geometry} material={materials._0000021323C0DA10} />
      <mesh geometry={nodes._0000021323C0EC70_IndexedFaceSet.geometry} material={materials._0000021323C0EC70} />
    </group>
  );
}

useGLTF.preload("/Serv-Z0-Sec3-transformed.glb");
