/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Serv-Z0-Sec5-cut4.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _0000025891063C00_IndexedFaceSet: THREE.Mesh;
    _00000258945B2C80_IndexedFaceSet: THREE.Mesh;
    _00000258A5E49EA0_IndexedFaceSet: THREE.Mesh;
    _00000258A5E4A710_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    _0000025891063C00: THREE.MeshStandardMaterial;
    _00000258945B2C80: THREE.MeshStandardMaterial;
    _00000258A5E49EA0: THREE.MeshStandardMaterial;
    _00000258A5E4A710: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Serv-Z0-Sec5-cut4-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._0000025891063C00_IndexedFaceSet.geometry} material={materials._0000025891063C00} />
      <mesh geometry={nodes._00000258945B2C80_IndexedFaceSet.geometry} material={materials._00000258945B2C80} />
      <mesh geometry={nodes._00000258A5E49EA0_IndexedFaceSet.geometry} material={materials._00000258A5E49EA0} />
      <mesh geometry={nodes._00000258A5E4A710_IndexedFaceSet.geometry} material={materials._00000258A5E4A710} />
    </group>
  );
}

useGLTF.preload("/Serv-Z0-Sec5-cut4-transformed.glb");
