/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Serv-Muon-SW-cut1.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _000002AC2BCB0770_IndexedFaceSet: THREE.Mesh;
    _000002AC2BCB6200_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    ["Material.030"]: THREE.MeshStandardMaterial;
    ["Material.032"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Serv-Muon-SW-cut1-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._000002AC2BCB0770_IndexedFaceSet.geometry} material={materials["Material.030"]} />
      <mesh geometry={nodes._000002AC2BCB6200_IndexedFaceSet.geometry} material={materials["Material.032"]} />
    </group>
  );
}

useGLTF.preload("/Serv-Muon-SW-cut1-transformed.glb");
