/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Serv-Z0-Sec1-cut1.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _000002195B8A15C0_IndexedFaceSet: THREE.Mesh;
    _000002195B8A3540_IndexedFaceSet: THREE.Mesh;
    _000002195B8A4E30_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    ["_000002195B8A15C0.001"]: THREE.MeshStandardMaterial;
    ["_000002195B8A3540.001"]: THREE.MeshStandardMaterial;
    ["_000002195B8A4E30.001"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Serv-Z0-Sec1-cut1-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._000002195B8A15C0_IndexedFaceSet.geometry} material={materials["_000002195B8A15C0.001"]} />
      <mesh geometry={nodes._000002195B8A3540_IndexedFaceSet.geometry} material={materials["_000002195B8A3540.001"]} />
      <mesh geometry={nodes._000002195B8A4E30_IndexedFaceSet.geometry} material={materials["_000002195B8A4E30.001"]} />
    </group>
  );
}

useGLTF.preload("/Serv-Z0-Sec1-cut1-transformed.glb");
