/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Serv-Z0-Sec3-cut4.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _0000025885C98D50_IndexedFaceSet: THREE.Mesh;
    _0000025887AD4080_IndexedFaceSet: THREE.Mesh;
    _00000258E6955920_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    ["_0000025885C98D50.001"]: THREE.MeshStandardMaterial;
    ["_0000025887AD4080.001"]: THREE.MeshStandardMaterial;
    ["_00000258E6955920.001"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Serv-Z0-Sec3-cut4-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._0000025885C98D50_IndexedFaceSet.geometry} material={materials["_0000025885C98D50.001"]} />
      <mesh geometry={nodes._0000025887AD4080_IndexedFaceSet.geometry} material={materials["_0000025887AD4080.001"]} />
      <mesh geometry={nodes._00000258E6955920_IndexedFaceSet.geometry} material={materials["_00000258E6955920.001"]} />
    </group>
  );
}

useGLTF.preload("/Serv-Z0-Sec3-cut4-transformed.glb");
