/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Small-Wheel-Hub-SideC-cut3.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0005: THREE.Mesh;
    Mesh_1005: THREE.Mesh;
  };
  materials: {
    ["Material_0.100"]: THREE.MeshStandardMaterial;
    ["Material_1.072"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Small-Wheel-Hub-SideC-cut3-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0005.geometry} material={materials["Material_0.100"]} />
      <mesh geometry={nodes.Mesh_1005.geometry} material={materials["Material_1.072"]} />
    </group>
  );
}

useGLTF.preload("/Small-Wheel-Hub-SideC-cut3-transformed.glb");
