/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Small-Wheel-Chambers-SideC-cut4.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0006: THREE.Mesh;
    Mesh_1004: THREE.Mesh;
    Mesh_2004: THREE.Mesh;
    Mesh_3004: THREE.Mesh;
  };
  materials: {
    ["Material_0.090"]: THREE.MeshStandardMaterial;
    ["Material_1.062"]: THREE.MeshStandardMaterial;
    ["Material_2.034"]: THREE.MeshStandardMaterial;
    ["Material_3.028"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Small-Wheel-Chambers-SideC-cut4-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0006.geometry} material={materials["Material_0.090"]} />
      <mesh geometry={nodes.Mesh_1004.geometry} material={materials["Material_1.062"]} />
      <mesh geometry={nodes.Mesh_2004.geometry} material={materials["Material_2.034"]} />
      <mesh geometry={nodes.Mesh_3004.geometry} material={materials["Material_3.028"]} />
    </group>
  );
}

useGLTF.preload("/Small-Wheel-Chambers-SideC-cut4-transformed.glb");
