/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Small-Wheel-Chambers-SideA-cut4.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0004: THREE.Mesh;
    Mesh_1002: THREE.Mesh;
    Mesh_2002: THREE.Mesh;
    Mesh_3002: THREE.Mesh;
  };
  materials: {
    ["Material_0.088"]: THREE.MeshStandardMaterial;
    ["Material_1.061"]: THREE.MeshStandardMaterial;
    ["Material_2.033"]: THREE.MeshStandardMaterial;
    ["Material_3.027"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Small-Wheel-Chambers-SideA-cut4-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0004.geometry} material={materials["Material_0.088"]} />
      <mesh geometry={nodes.Mesh_1002.geometry} material={materials["Material_1.061"]} />
      <mesh geometry={nodes.Mesh_2002.geometry} material={materials["Material_2.033"]} />
      <mesh geometry={nodes.Mesh_3002.geometry} material={materials["Material_3.027"]} />
    </group>
  );
}

useGLTF.preload("/Small-Wheel-Chambers-SideA-cut4-transformed.glb");
