/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Small-Wheel-Hub-SideA-cut2.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0001: THREE.Mesh;
    Mesh_1001: THREE.Mesh;
  };
  materials: {
    ["Material_0.095"]: THREE.MeshStandardMaterial;
    ["Material_1.067"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Small-Wheel-Hub-SideA-cut2-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0001.geometry} material={materials["Material_0.095"]} />
      <mesh geometry={nodes.Mesh_1001.geometry} material={materials["Material_1.067"]} />
    </group>
  );
}

useGLTF.preload("/Small-Wheel-Hub-SideA-cut2-transformed.glb");
