/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/TGC-SideC-cut4.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0014: THREE.Mesh;
    Mesh_1014: THREE.Mesh;
  };
  materials: {
    ["Material_0.123"]: THREE.MeshStandardMaterial;
    ["Material_1.087"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/TGC-SideC-cut4-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 0, Math.PI]}>
        <mesh geometry={nodes.Mesh_0014.geometry} material={materials["Material_0.123"]} />
        <mesh geometry={nodes.Mesh_1014.geometry} material={materials["Material_1.087"]} />
      </group>
    </group>
  );
}

useGLTF.preload("/TGC-SideC-cut4-transformed.glb");
