/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/TGC-SideA-cut2.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0012: THREE.Mesh;
    Mesh_1012: THREE.Mesh;
  };
  materials: {
    ["Material_0.122"]: THREE.MeshStandardMaterial;
    ["Material_1.086"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/TGC-SideA-cut2-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 0, Math.PI]} scale={[-1, 1, 1]}>
        <mesh geometry={nodes.Mesh_0012.geometry} material={materials["Material_0.122"]} />
        <mesh geometry={nodes.Mesh_1012.geometry} material={materials["Material_1.086"]} />
      </group>
    </group>
  );
}

useGLTF.preload("/TGC-SideA-cut2-transformed.glb");
