/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/TGC2-SideA-cut4.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    _0000022A61E260D0_IndexedFaceSet: THREE.Mesh;
    _0000022A0BE060F0_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    ["Material.007"]: THREE.MeshStandardMaterial;
    ["Material.008"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/TGC2-SideA-cut4-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes._0000022A61E260D0_IndexedFaceSet.geometry}
        material={materials["Material.007"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes._0000022A0BE060F0_IndexedFaceSet.geometry}
        material={materials["Material.008"]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/TGC2-SideA-cut4-transformed.glb");
