/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/TGC2-SideC-cut2.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0022: THREE.Mesh;
    Mesh_1022: THREE.Mesh;
  };
  materials: {
    ["Material_0.115"]: THREE.MeshStandardMaterial;
    ["Material_1.079"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/TGC2-SideC-cut2-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 0, Math.PI]} scale={[-1, 1, 1]}>
        <mesh geometry={nodes.Mesh_0022.geometry} material={materials["Material_0.115"]} />
        <mesh geometry={nodes.Mesh_1022.geometry} material={materials["Material_1.079"]} />
      </group>
    </group>
  );
}

useGLTF.preload("/TGC2-SideC-cut2-transformed.glb");
