/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Tile-End-Cap-SideA-cut2.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0: THREE.Mesh;
    Mesh_1: THREE.Mesh;
    Mesh_2: THREE.Mesh;
  };
  materials: {
    ["Material_0.131"]: THREE.MeshStandardMaterial;
    ["Material_1.095"]: THREE.MeshStandardMaterial;
    ["Material_2.039"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Tile-End-Cap-SideA-cut2-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0.geometry} material={materials["Material_0.131"]} />
      <mesh geometry={nodes.Mesh_1.geometry} material={materials["Material_1.095"]} />
      <mesh geometry={nodes.Mesh_2.geometry} material={materials["Material_2.039"]} />
    </group>
  );
}

useGLTF.preload("/Tile-End-Cap-SideA-cut2-transformed.glb");
