/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Tile-End-Cap-SideC-cut2.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0014: THREE.Mesh;
    Mesh_1015: THREE.Mesh;
    Mesh_2009: THREE.Mesh;
  };
  materials: {
    ["Material_0.135"]: THREE.MeshStandardMaterial;
    ["Material_1.099"]: THREE.MeshStandardMaterial;
    ["Material_2.043"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Tile-End-Cap-SideC-cut2-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0014.geometry} material={materials["Material_0.135"]} />
      <mesh geometry={nodes.Mesh_1015.geometry} material={materials["Material_1.099"]} />
      <mesh geometry={nodes.Mesh_2009.geometry} material={materials["Material_2.043"]} />
    </group>
  );
}

useGLTF.preload("/Tile-End-Cap-SideC-cut2-transformed.glb");
