/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Tile-Barrel.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0042: THREE.Mesh;
    Mesh_1031: THREE.Mesh;
  };
  materials: {
    ["Material_0.126"]: THREE.MeshStandardMaterial;
    ["Material_1.090"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Tile-Barrel-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0042.geometry} material={materials["Material_0.126"]} />
      <mesh geometry={nodes.Mesh_1031.geometry} material={materials["Material_1.090"]} />
    </group>
  );
}

useGLTF.preload("/Tile-Barrel-transformed.glb");
