/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Tile-End-Cap-SideC-cut4.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0012: THREE.Mesh;
    Mesh_1013: THREE.Mesh;
    Mesh_2007: THREE.Mesh;
  };
  materials: {
    ["Material_0.133"]: THREE.MeshStandardMaterial;
    ["Material_1.097"]: THREE.MeshStandardMaterial;
    ["Material_2.041"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Tile-End-Cap-SideC-cut4-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0012.geometry} material={materials["Material_0.133"]} />
      <mesh geometry={nodes.Mesh_1013.geometry} material={materials["Material_1.097"]} />
      <mesh geometry={nodes.Mesh_2007.geometry} material={materials["Material_2.041"]} />
    </group>
  );
}

useGLTF.preload("/Tile-End-Cap-SideC-cut4-transformed.glb");
