/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Tile-End-Cap-SideC-cut1.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0013: THREE.Mesh;
    Mesh_1014: THREE.Mesh;
    Mesh_2008: THREE.Mesh;
  };
  materials: {
    ["Material_0.134"]: THREE.MeshStandardMaterial;
    ["Material_1.098"]: THREE.MeshStandardMaterial;
    ["Material_2.042"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Tile-End-Cap-SideC-cut1-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0013.geometry} material={materials["Material_0.134"]} />
      <mesh geometry={nodes.Mesh_1014.geometry} material={materials["Material_1.098"]} />
      <mesh geometry={nodes.Mesh_2008.geometry} material={materials["Material_2.042"]} />
    </group>
  );
}

useGLTF.preload("/Tile-End-Cap-SideC-cut1-transformed.glb");
