/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Tile-End-Cap-SideA-cut3.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0010: THREE.Mesh;
    Mesh_1011: THREE.Mesh;
    Mesh_2005: THREE.Mesh;
  };
  materials: {
    ["Material_0.132"]: THREE.MeshStandardMaterial;
    ["Material_1.096"]: THREE.MeshStandardMaterial;
    ["Material_2.040"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Tile-End-Cap-SideA-cut3-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0010.geometry} material={materials["Material_0.132"]} />
      <mesh geometry={nodes.Mesh_1011.geometry} material={materials["Material_1.096"]} />
      <mesh geometry={nodes.Mesh_2005.geometry} material={materials["Material_2.040"]} />
    </group>
  );
}

useGLTF.preload("/Tile-End-Cap-SideA-cut3-transformed.glb");
