/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/TRT-SideA-cut4.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0011: THREE.Mesh;
    Mesh_1011: THREE.Mesh;
  };
  materials: {
    ["Material_0.143"]: THREE.MeshStandardMaterial;
    ["Material_1.113"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/TRT-SideA-cut4-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0011.geometry} material={materials["Material_0.143"]} />
      <mesh geometry={nodes.Mesh_1011.geometry} material={materials["Material_1.113"]} />
    </group>
  );
}

useGLTF.preload("/TRT-SideA-cut4-transformed.glb");
