/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/USA15-cut1.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_1001: THREE.Mesh;
    Mesh_2001: THREE.Mesh;
  };
  materials: {
    ["Material_1.120"]: THREE.MeshStandardMaterial;
    ["Material_2.050"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/USA15-cut1-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_1001.geometry} material={materials["Material_1.120"]} />
      <mesh geometry={nodes.Mesh_2001.geometry} material={materials["Material_2.050"]} />
    </group>
  );
}

useGLTF.preload("/USA15-cut1-transformed.glb");
