/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/UX15-cut1.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0007: THREE.Mesh;
    Mesh_3002: THREE.Mesh;
  };
  materials: {
    ["Material_0.153"]: THREE.MeshStandardMaterial;
    ["Material_3.032"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/UX15-cut1-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0007.geometry} material={materials["Material_0.153"]} />
      <mesh geometry={nodes.Mesh_3002.geometry} material={materials["Material_3.032"]} />
    </group>
  );
}

useGLTF.preload("/UX15-cut1-transformed.glb");
