/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/UX15-cut3.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0009: THREE.Mesh;
    Mesh_2008: THREE.Mesh;
  };
  materials: {
    ["Material_0.154"]: THREE.MeshStandardMaterial;
    ["Material_2.053"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/UX15-cut3-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0009.geometry} material={materials["Material_0.154"]} />
      <mesh geometry={nodes.Mesh_2008.geometry} material={materials["Material_2.053"]} />
    </group>
  );
}

useGLTF.preload("/UX15-cut3-transformed.glb");
