/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/UX15.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_1007: THREE.Mesh;
    Mesh_2005: THREE.Mesh;
  };
  materials: {
    ["Material_1.123"]: THREE.MeshStandardMaterial;
    ["Material_2.051"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/UX15-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_1007.geometry} material={materials["Material_1.123"]} />
      <mesh geometry={nodes.Mesh_2005.geometry} material={materials["Material_2.051"]} />
    </group>
  );
}

useGLTF.preload("/UX15-transformed.glb");
