/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/VR-Cavern.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["S_E17012190-001"]: THREE.Mesh;
    S_Mesh_0: THREE.Mesh;
    ["S_Mesh_0-001"]: THREE.Mesh;
    ["S_Mesh_0-012"]: THREE.Mesh;
  };
  materials: {
    ["Material_E17012190-001.001"]: THREE.MeshStandardMaterial;
    Material_Mesh_0: THREE.MeshStandardMaterial;
    ["Material_Mesh_0-001"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/VR-Cavern-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["S_E17012190-001"].geometry}
        material={materials["Material_E17012190-001.001"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.S_Mesh_0.geometry} material={materials.Material_Mesh_0} rotation={[Math.PI / 2, 0, 0]} />
      <mesh
        geometry={nodes["S_Mesh_0-001"].geometry}
        material={materials["Material_Mesh_0-001"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S_Mesh_0-012"].geometry}
        material={materials["Material_E17012190-001.001"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/VR-Cavern-transformed.glb");
