/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/VR-Calo.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["S_Mesh_0-087"]: THREE.Mesh;
    ["S_Mesh_0-088"]: THREE.Mesh;
    ["S_Mesh_0-093"]: THREE.Mesh;
  };
  materials: {
    ["Material_Mesh_0-087"]: THREE.MeshStandardMaterial;
    ["Material_Mesh_0-088"]: THREE.MeshStandardMaterial;
    ["Material_Mesh_0-093"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/VR-Calo-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["S_Mesh_0-087"].geometry}
        material={materials["Material_Mesh_0-087"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S_Mesh_0-088"].geometry}
        material={materials["Material_Mesh_0-088"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S_Mesh_0-093"].geometry}
        material={materials["Material_Mesh_0-093"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/VR-Calo-transformed.glb");
