/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/VR-Magnets.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["S_Mesh_0-119"]: THREE.Mesh;
    ["S__046AD8E8-003"]: THREE.Mesh;
    ["S__0536A8B8-003"]: THREE.Mesh;
    ["S__05CE1148-003"]: THREE.Mesh;
    ["S__1F089968-003"]: THREE.Mesh;
    ["S__1F0C5598-003"]: THREE.Mesh;
  };
  materials: {
    ["Material_Mesh_0-119"]: THREE.MeshStandardMaterial;
    ["Material__046AD8E8-003"]: THREE.MeshStandardMaterial;
    ["Material__0536A8B8-003"]: THREE.MeshStandardMaterial;
    ["Material__05CE1148-003"]: THREE.MeshStandardMaterial;
    ["Material__1F089968-003"]: THREE.MeshStandardMaterial;
    ["Material__1F0C5598-003"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/VR-Magnets-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["S_Mesh_0-119"].geometry}
        material={materials["Material_Mesh_0-119"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S__046AD8E8-003"].geometry}
        material={materials["Material__046AD8E8-003"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S__0536A8B8-003"].geometry}
        material={materials["Material__0536A8B8-003"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S__05CE1148-003"].geometry}
        material={materials["Material__05CE1148-003"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S__1F089968-003"].geometry}
        material={materials["Material__1F089968-003"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S__1F0C5598-003"].geometry}
        material={materials["Material__1F0C5598-003"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/VR-Magnets-transformed.glb");
