/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/VR-Support.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    ["S_Mesh_0-156"]: THREE.Mesh;
    ["S_Mesh_1-011"]: THREE.Mesh;
    ["S_Mesh_1-141"]: THREE.Mesh;
    ["S_Mesh_2-009"]: THREE.Mesh;
    ["S_Mesh_2-070"]: THREE.Mesh;
    ["S_Mesh_3-003"]: THREE.Mesh;
    S_Mesh_4: THREE.Mesh;
    S_Mesh_5: THREE.Mesh;
  };
  materials: {
    ["Material_Mesh_0-156.001"]: THREE.MeshStandardMaterial;
    ["Material_Mesh_1-011"]: THREE.MeshStandardMaterial;
    ["Material_Mesh_1-141.001"]: THREE.MeshStandardMaterial;
    ["Material_Mesh_2-009"]: THREE.MeshStandardMaterial;
    ["Material_Mesh_2-070.001"]: THREE.MeshStandardMaterial;
    ["Material_Mesh_3-003"]: THREE.MeshStandardMaterial;
    Material_Mesh_4: THREE.MeshStandardMaterial;
    Material_Mesh_5: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/VR-Support-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes["S_Mesh_0-156"].geometry}
        material={materials["Material_Mesh_0-156.001"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S_Mesh_1-011"].geometry}
        material={materials["Material_Mesh_1-011"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S_Mesh_1-141"].geometry}
        material={materials["Material_Mesh_1-141.001"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S_Mesh_2-009"].geometry}
        material={materials["Material_Mesh_2-009"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S_Mesh_2-070"].geometry}
        material={materials["Material_Mesh_2-070.001"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes["S_Mesh_3-003"].geometry}
        material={materials["Material_Mesh_3-003"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh geometry={nodes.S_Mesh_4.geometry} material={materials.Material_Mesh_4} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.S_Mesh_5.geometry} material={materials.Material_Mesh_5} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  );
}

useGLTF.preload("/VR-Support-transformed.glb");
