/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Warm-Structure-cut2.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_0002: THREE.Mesh;
    Mesh_1002: THREE.Mesh;
  };
  materials: {
    ["Material_0.157"]: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/Warm-Structure-cut2-transformed.glb") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0002.geometry} material={materials["Material_0.157"]} />
      <mesh geometry={nodes.Mesh_1002.geometry} material={materials["Material_0.157"]} />
    </group>
  );
}

useGLTF.preload("/Warm-Structure-cut2-transformed.glb");
