/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/End-Cap-Toroid-SideA-cut3.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { modelsUrl } from "../utils/preloadModels";

type GLTFResult = GLTF & {
  nodes: {
    S__0469C088: THREE.Mesh;
    S__046A9078: THREE.Mesh;
    S__047E7608: THREE.Mesh;
    S__04CB5DB8: THREE.Mesh;
    S__04CC2A58: THREE.Mesh;
  };
  materials: {
    ["Material__0469C088.005"]: THREE.MeshStandardMaterial;
    ["Material__046A9078.005"]: THREE.MeshStandardMaterial;
    ["Material__047E7608.005"]: THREE.MeshStandardMaterial;
    ["Material__04CB5DB8.005"]: THREE.MeshStandardMaterial;
    ["Material__04CC2A58.005"]: THREE.MeshStandardMaterial;
  };
};

/**
 *
 * @param props
 */
export function EndCapToroidSideACut3(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(`${modelsUrl}/end-cap-toroid-sidea-cut3.glb`) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.S__0469C088.geometry}
        material={materials["Material__0469C088.005"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.S__046A9078.geometry}
        material={materials["Material__046A9078.005"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.S__047E7608.geometry}
        material={materials["Material__047E7608.005"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.S__04CB5DB8.geometry}
        material={materials["Material__04CB5DB8.005"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.S__04CC2A58.geometry}
        material={materials["Material__04CC2A58.005"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}
