/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Lar-EMEC-SideC-cut3.glb --transform --t
*/

import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { modelsUrl } from "../utils/preloadModels";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_1003: THREE.Mesh;
    Mesh_3004_1: THREE.Mesh;
    Mesh_3004_2: THREE.Mesh;
  };
  materials: {
    ["Material_1.002"]: THREE.MeshStandardMaterial;
    ["Material_3.004"]: THREE.MeshStandardMaterial;
  };
};

/**
 *
 * @param props
 */
export function LarEmecSideCCut3(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(`${modelsUrl}/lar-emec-sidec-cut3.glb`) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_1003.geometry} material={materials["Material_1.002"]} />
      <mesh geometry={nodes.Mesh_3004_1.geometry} material={materials["Material_3.004"]} />
      <mesh geometry={nodes.Mesh_3004_2.geometry} material={materials["Material_3.004"]} />
    </group>
  );
}
