/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Lar-EMEC-SideA-cut3.glb --transform --t
*/

import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { modelsUrl } from "../utils/preloadModels";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_1001_1: THREE.Mesh;
    Mesh_1001_2: THREE.Mesh;
    Mesh_3002: THREE.Mesh;
  };
  materials: {
    ["Material_1.001"]: THREE.MeshStandardMaterial;
    ["Material_3.003"]: THREE.MeshStandardMaterial;
  };
};

/**
 *
 * @param props
 */
export function LarEmecSideACut3(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(`${modelsUrl}/lar-emec-sidea-cut3.glb`) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_3002.geometry} material={materials["Material_3.003"]} />
      <mesh geometry={nodes.Mesh_1001_1.geometry} material={materials["Material_1.001"]} />
      <mesh geometry={nodes.Mesh_1001_2.geometry} material={materials["Material_1.001"]} />
    </group>
  );
}
