/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/iraklikverenchkhiladze/Desktop/threeinit/src/models/SCT-BAR-cut3.glb --transform --t
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

import applyDefaultsToModel from "../utils/applyDefaultsToModel.utils";
import { modelsUrl } from "../utils/preloadModels";

type GLTFResult = GLTF & {
  nodes: {
    Mesh_2011: THREE.Mesh;
    Mesh_3008: THREE.Mesh;
  };
  materials: {
    ["Material_2.022"]: THREE.MeshStandardMaterial;
    ["Material_3.016"]: THREE.MeshStandardMaterial;
  };
};

/**
 *
 * @param props
 */
export function SctBar3(props: JSX.IntrinsicElements["group"]): JSX.Element {
  const { nodes, materials } = useGLTF(`${modelsUrl}/sct-bar-cut3.glb`) as GLTFResult;

  applyDefaultsToModel(materials);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_2011.geometry} material={materials["Material_2.022"]} />
      <mesh geometry={nodes.Mesh_3008.geometry} material={materials["Material_3.016"]} />
    </group>
  );
}
