/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 serv-muon-cable-trays-inside-barrel-cut3.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { modelsUrl } from "../utils/preloadModels";

type GLTFResult = GLTF & {
  nodes: {
    Cabble_Trays_Inside_Barrel_cut3: THREE.Mesh;
  };
  materials: {
    ["Material_None.003"]: THREE.MeshStandardMaterial;
  };
};

/**
 *
 * @param props
 */
export function ServMuonCableTraysInsideBarelCut3(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(`${modelsUrl}/serv-muon-cable-trays-inside-barrel-cut3.glb`) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cabble_Trays_Inside_Barrel_cut3.geometry}
        material={materials["Material_None.003"]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}
