/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Serv-Muon-Barrel-Calo-Ele-Boxes-cut3.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { modelsUrl } from "../utils/preloadModels";

type GLTFResult = GLTF & {
  nodes: {
    Electrical_Boxes_Barrel_cut3: THREE.Mesh;
  };
  materials: {
    ["Material_DB0271410.005"]: THREE.MeshStandardMaterial;
  };
};

/**
 *
 * @param props
 */
export function ServMuonBarrelCaloEleBoxesCut3(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(`${modelsUrl}/serv-muon-barrel-calo-ele-boxes-cut3.glb`) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Electrical_Boxes_Barrel_cut3.geometry} material={materials["Material_DB0271410.005"]} />
    </group>
  );
}
