/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 /Users/nzurashv/Desktop/work/tracercentral/resources/geo/Serv-Muon-SW-cut3.glb --transform --t
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { modelsUrl } from "../utils/preloadModels";

type GLTFResult = GLTF & {
  nodes: {
    _000002AC2BCA5F70_IndexedFaceSet: THREE.Mesh;
    _000002AC2BCAB610_IndexedFaceSet: THREE.Mesh;
  };
  materials: {
    ["Material.035"]: THREE.MeshStandardMaterial;
    ["Material.036"]: THREE.MeshStandardMaterial;
  };
};

/**
 *
 * @param props
 */
export function ServMuonSwCut3(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(`${modelsUrl}/serv-muon-sw-cut3.glb`) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes._000002AC2BCA5F70_IndexedFaceSet.geometry} material={materials["Material.035"]} />
      <mesh geometry={nodes._000002AC2BCAB610_IndexedFaceSet.geometry} material={materials["Material.036"]} />
    </group>
  );
}
